"""
prepare_kinematics.py — ProcessSpec JSON → kinematics.m

Generates a Mathematica kinematics file containing:
  - OnShell[] rules (set mass^2 = mass_symbol^2 for each particle)
  - Mandelstam substitution rules (if mandelstam section present)
  - Neglect[] calls (if excludes contains mass symbols to neglect)

The output is a pure string template; no Wolfram execution required.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Union


def generate_kinematics_m(processspec_path: Union[str, Path]) -> str:
    """Read ProcessSpec.json and return the full kinematics.m content."""
    path = Path(processspec_path)
    with open(path) as f:
        spec = json.load(f)

    lines = [
        "(* kinematics.m — generated by prepare_kinematics.py *)",
        "(* ProcessSpec: " + spec.get("schema_version", "processspec/v1") + " *)",
        "",
    ]

    # Collect all particles (in + out)
    particles_in = spec.get("particles", {}).get("in", [])
    particles_out = spec.get("particles", {}).get("out", [])
    all_particles = particles_in + particles_out

    # OnShell rules: p_i^2 = mass_symbol^2
    onshell_lines = []
    for i, p in enumerate(all_particles, start=1):
        mass_sym = p.get("mass_symbol", "0")
        onshell_lines.append(f"  FourMomentum[Outgoing, {i}]^2 -> {mass_sym}^2")

    if onshell_lines:
        lines.append("(* On-shell conditions *)")
        lines.append("OnShell[")
        lines.append(",\n".join(onshell_lines))
        lines.append("];")
        lines.append("")

    # Mandelstam variables
    mandelstam = spec.get("mandelstam", {})
    if mandelstam:
        lines.append("(* Mandelstam substitutions *)")
        mandel_rules = []
        if "s" in mandelstam:
            mandel_rules.append(f"  MandelstamS -> {mandelstam['s']}")
        if "t" in mandelstam:
            mandel_rules.append(f"  MandelstamT -> {mandelstam['t']}")
        if "u" in mandelstam:
            mandel_rules.append(f"  MandelstamU -> {mandelstam['u']}")
        if mandel_rules:
            lines.append("Mandelstam[")
            lines.append(",\n".join(mandel_rules))
            lines.append("];")
            lines.append("")

    # Neglect: masses in the excludes list that look like mass symbols
    excludes = spec.get("excludes", [])
    # Filter to entries that look like mass symbols (uppercase start or all-caps)
    neglect_masses = [e for e in excludes if e and e[0].isupper()]
    if neglect_masses:
        lines.append("(* Neglect light masses *)")
        for mass in neglect_masses:
            lines.append(f"Neglect[{mass}];")
        lines.append("")

    lines.append("(* End of kinematics.m *)")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: prepare_kinematics.py <ProcessSpec.json>", file=sys.stderr)
        sys.exit(1)
    print(generate_kinematics_m(sys.argv[1]), end="")
