"""MadGraph5 batch scripting utilities.

Generate proc_card.dat content and bash launch scripts for MG5 runs.
Library functions Claude composes per-task — not CLI executables.
"""

from __future__ import annotations


def generate_proc_card(
    processes: list[str],
    model: str = "sm",
    output_name: str = "output",
    multiparticle_defs: dict[str, str] | None = None,
) -> str:
    """Build proc_card.dat content.

    Args:
        processes: List of process strings. First becomes 'generate',
            rest become 'add process'.
            Example: ["p p > t t~", "p p > t t~ j"]
        model: Model name, e.g. 'sm', 'mssm', '2hdm', 'sm-no_b_mass'.
        output_name: Name for the MG5 output directory.
        multiparticle_defs: Optional extra multiparticle definitions.
            Example: {"vl": "ve vm vt", "vl~": "ve~ vm~ vt~"}

    Returns:
        Complete proc_card.dat content as a string.
    """
    lines = [f"import model {model}"]

    if multiparticle_defs:
        for name, definition in multiparticle_defs.items():
            lines.append(f"define {name} = {definition}")

    for i, proc in enumerate(processes):
        cmd = "generate" if i == 0 else "add process"
        lines.append(f"{cmd} {proc}")

    lines.append(f"output {output_name}")
    return "\n".join(lines) + "\n"


def generate_launch_script(
    proc_dir: str,
    param_card: str | None = None,
    run_card: str | None = None,
    nevents: int = 10000,
    seed: int = 0,
    run_name: str = "run_01",
) -> str:
    """Build a bash script that launches a MG5 run.

    Args:
        proc_dir: Path to the MG5 output directory.
        param_card: Path to custom param_card.dat (None = use default).
        run_card: Path to custom run_card.dat (None = use default).
        nevents: Number of events to generate.
        seed: Random seed (0 = automatic).
        run_name: Name tag for this run.

    Returns:
        Bash script content as a string.
    """
    mg5_lines = [
        f"launch {proc_dir}",
        f"  set nevents {nevents}",
        f"  set iseed {seed}",
        f"  set run_tag {run_name}",
    ]

    if param_card:
        mg5_lines.append(f"  {param_card}")
    if run_card:
        mg5_lines.append(f"  {run_card}")

    mg5_lines.append("done")
    mg5_script = "\n".join(mg5_lines)

    return f"""#!/usr/bin/env bash
# MadGraph5 launch script — generated by monte-carlo-tools
set -euo pipefail

MG5_DIR="${{MG5_DIR:-$(which mg5_aMC 2>/dev/null | xargs dirname)/..}}"
PROC_DIR="{proc_dir}"

MG5_CMD=$(mktemp /tmp/mg5_launch_XXXXXX.txt)
cat > "$MG5_CMD" << 'MG5EOF'
{mg5_script}
MG5EOF

echo "Launching MG5: $PROC_DIR (nevents={nevents}, seed={seed})"
python3 "$MG5_DIR/bin/mg5_aMC" "$MG5_CMD"

echo "Done. Output in: $PROC_DIR/Events/{run_name}/"
rm -f "$MG5_CMD"
"""
