"""main_c_template.py — deterministic C driver generator for micrOMEGAs.

Generates main.c source for each subcommand. Uses textwrap.dedent + f-strings.
No template engine dependency. Output is deterministic byte-for-byte given the
same inputs.

All generated drivers embed:
  HEPPH_MICROMEGAS_SEED=42  (getenv fallback to 42)

Public API:
    render(subcommand: str, spec: dict, dm: dict, halo: dict | None) -> str

    subcommand: "relic" | "scatter" | "annihilate" | "indirect"
    spec: loaded spec.yaml dict (for dm_candidate, nucleon_form_factors, etc.)
    dm: {"pdg": int, "name": str, "mass_gev": float}
    halo: {"model": "shm", ...} or None

C API signatures verified against micrOMEGAs 6.0.5 source:
  - darkOmega(double *Xf, int fast, double Beps)  →  double
      declared in sources/micromegas.h (extern double darkOmega(...))
  - nucleonAmplitudes(int pdg, double *pAsi, double *nAsi, double *pAsd, double *nAsd) → int
      declared in sources/micromegas.h
  - calcSpectrum(int key, double *Emin, double *Emax, double *sigmav,
                 double *SpA, double *SpE, double *SpP, double *SpNe, FILE *f) → double
      declared in sources/micromegas.h (calcSpectrum function)
  - vSigma(double v, double cut, int fast) → double
      declared in sources/micromegas.h (annihilation cross section)

Note: The exact function signatures are documented here as of 6.0.5. The
generated code may require include-path adjustments when building inside a
non-standard project layout.
"""
import sys
assert sys.version_info >= (3, 10), "hephaestus requires Python >= 3.10"

import textwrap

# PRNG seed embedded in all generated drivers.
_SEED = 42
_PLANCK_OMEGA = 0.120
_PLANCK_SIGMA = 0.0012


def render(
    subcommand: str,
    spec: dict | None = None,
    dm: dict | None = None,
    halo: dict | None = None,
) -> str:
    """Render a main.c driver for the given subcommand.

    Args:
        subcommand: One of "relic", "scatter", "annihilate", "indirect".
        spec:       Loaded spec.yaml dict (used for dm_candidate, form_factors).
        dm:         DM candidate: {"pdg": int, "name": str, "mass_gev": float}.
        halo:       Halo model dict or None (defaults to SHM).

    Returns:
        Complete main.c source as a string.

    Raises:
        ValueError: if subcommand is not recognized.
    """
    if subcommand not in ("relic", "scatter", "annihilate", "indirect"):
        raise ValueError(
            f"Unknown subcommand {subcommand!r}. "
            "Expected: relic, scatter, annihilate, indirect."
        )

    spec = spec or {}
    dm = dm or {"pdg": 0, "name": "DM", "mass_gev": 0.0}
    halo = halo or {}

    dm_pdg = int(dm.get("pdg", 0))
    dm_name = str(dm.get("name", "DM"))
    dm_mass = float(dm.get("mass_gev", 0.0))

    header = _render_header(subcommand, dm_name, dm_pdg)
    body = _render_body(subcommand, dm_pdg, dm_mass)
    return header + body


def _render_header(subcommand: str, dm_name: str, dm_pdg: int) -> str:
    return textwrap.dedent(f"""\
        /* micrOMEGAs driver — generated by hephaestus /micromegas {subcommand}
         * DM candidate: {dm_name} (PDG {dm_pdg})
         * HEPPH_MICROMEGAS_SEED: {_SEED}
         * DO NOT EDIT — regenerate via scripts/main_c_template.py
         */
        #include <stdio.h>
        #include <stdlib.h>
        #include <math.h>
        #include "micromegas.h"
        #include "micromegas_aux.h"
        #include "pmodel.h"

        int main(int argc, char **argv) {{
            char *pname = FILE_NAME;
            int err;
            double Omega, Xf;

            /* Seed from environment (default {_SEED}) */
            const char *seed_env = getenv("HEPPH_MICROMEGAS_SEED");
            int seed = seed_env ? atoi(seed_env) : {_SEED};
            srand(seed);

            err = sortOddParticles(pname);
            if (err != 0) {{
                fprintf(stderr, "sortOddParticles failed: %d\\n", err);
                return 1;
            }}

    """)


def _render_body(subcommand: str, dm_pdg: int, dm_mass: float) -> str:
    if subcommand == "relic":
        return textwrap.dedent(f"""\
                /* Relic density calculation */
                double Beps = 1.E-6;
                Omega = darkOmega(&Xf, 1, Beps);
                printf("Xf= %e\\n", Xf);
                printf("Omega h^2 = %e\\n", Omega);
                printf("Planck target: {_PLANCK_OMEGA:.3f} +/- {_PLANCK_SIGMA:.4f}\\n");
                if (Omega > 0 && isfinite(Omega)) {{
                    double pull = (Omega - {_PLANCK_OMEGA}) / {_PLANCK_SIGMA};
                    printf("Pull = %.2f sigma\\n", pull);
                }}
                return 0;
            }}
        """)

    if subcommand == "scatter":
        return textwrap.dedent(f"""\
                /* Direct detection cross-sections */
                double pAsi, nAsi, pAsd, nAsd;
                int pdg_dm = {dm_pdg};
                err = nucleonAmplitudes(pdg_dm, &pAsi, &nAsi, &pAsd, &nAsd);
                if (err != 0) {{
                    fprintf(stderr, "nucleonAmplitudes failed: %d\\n", err);
                    return 1;
                }}
                /* Convert amplitudes to cross-sections: σ = A² * (μ_N)² / π */
                /* micrOMEGAs returns pAsi etc. as amplitudes in GeV^-2 */
                double mN = 0.938272;  /* nucleon mass GeV */
                double mDM = {dm_mass:.6f};
                double mu_p = mDM * mN / (mDM + mN);
                double mu_n = mu_p;  /* approximation for proton ≈ neutron */
                double GeVm2_to_cm2 = 3.894e-28;  /* 1 GeV^-2 = 3.894e-28 cm^2 */
                double sig_si_p = pAsi * pAsi * mu_p * mu_p / M_PI * GeVm2_to_cm2;
                double sig_si_n = nAsi * nAsi * mu_n * mu_n / M_PI * GeVm2_to_cm2;
                double sig_sd_p = pAsd * pAsd * 3.0 * mu_p * mu_p / M_PI * GeVm2_to_cm2;
                double sig_sd_n = nAsd * nAsd * 3.0 * mu_n * mu_n / M_PI * GeVm2_to_cm2;
                printf("sigma_SI(p) = %e cm^2\\n", sig_si_p);
                printf("sigma_SI(n) = %e cm^2\\n", sig_si_n);
                printf("sigma_SD(p) = %e cm^2\\n", sig_sd_p);
                printf("sigma_SD(n) = %e cm^2\\n", sig_sd_n);
                return 0;
            }}
        """)

    if subcommand == "annihilate":
        return textwrap.dedent(f"""\
                /* Annihilation cross-section at v→0 */
                double v = 0.0;
                double cut = 0.01;
                double sv = vSigma(v, cut, 0);
                printf("sigma_v(v=0) = %e cm^3/s\\n", sv);

                /* Channel breakdown */
                double Beps = 1.E-6;
                Omega = darkOmega(&Xf, 1, Beps);
                printf("Omega h^2 = %e\\n", Omega);
                printf("Xf= %e\\n", Xf);

                /* Print channel fractions */
                sortOddParticles(pname);
                return 0;
            }}
        """)

    if subcommand == "indirect":
        return textwrap.dedent(f"""\
                /* Indirect detection spectra */
                double Emin = 1.0, Emax = {dm_mass:.1f} / 2.0;
                if (Emax <= Emin) Emax = Emin * 100.0;
                double sigmav_spec;
                double SpA[250], SpE[250], SpP[250], SpNe[250];
                err = calcSpectrum(3 /* gamma+e+pbar */, &Emin, &Emax, &sigmav_spec,
                                   SpA, SpE, SpP, SpNe, NULL);
                if (err != 0) {{
                    fprintf(stderr, "calcSpectrum failed: %d\\n", err);
                    return 1;
                }}
                printf("sigma_v(v=0) = %e cm^3/s\\n", sigmav_spec);

                /* Relic (needed for context) */
                double Beps = 1.E-6;
                Omega = darkOmega(&Xf, 1, Beps);
                printf("Omega h^2 = %e\\n", Omega);
                printf("Xf= %e\\n", Xf);
                return 0;
            }}
        """)

    raise ValueError(f"Unreachable: {subcommand!r}")


if __name__ == "__main__":
    import json as _json
    print("module: main_c_template, status: importable")
