/* micrOMEGAs driver — generated by hephaestus /micromegas annihilate
 * DM candidate: S (PDG 9000001)
 * HEPPH_MICROMEGAS_SEED: 42
 * DO NOT EDIT — regenerate via scripts/main_c_template.py
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "micromegas.h"
#include "micromegas_aux.h"
#include "pmodel.h"

int main(int argc, char **argv) {
    char *pname = FILE_NAME;
    int err;
    double Omega, Xf;

    /* Seed from environment (default 42) */
    const char *seed_env = getenv("HEPPH_MICROMEGAS_SEED");
    int seed = seed_env ? atoi(seed_env) : 42;
    srand(seed);

    err = sortOddParticles(pname);
    if (err != 0) {
        fprintf(stderr, "sortOddParticles failed: %d\n", err);
        return 1;
    }

    /* Annihilation cross-section at v→0 */
    double v = 0.0;
    double cut = 0.01;
    double sv = vSigma(v, cut, 0);
    printf("sigma_v(v=0) = %e cm^3/s\n", sv);

    /* Channel breakdown */
    double Beps = 1.E-6;
    Omega = darkOmega(&Xf, 1, Beps);
    printf("Omega h^2 = %e\n", Omega);
    printf("Xf= %e\n", Xf);

    /* Print channel fractions */
    sortOddParticles(pname);
    return 0;
}
