/* micrOMEGAs driver — generated by hephaestus /micromegas indirect
 * DM candidate: S (PDG 9000001)
 * HEPPH_MICROMEGAS_SEED: 42
 * DO NOT EDIT — regenerate via scripts/main_c_template.py
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "micromegas.h"
#include "micromegas_aux.h"
#include "pmodel.h"

int main(int argc, char **argv) {
    char *pname = FILE_NAME;
    int err;
    double Omega, Xf;

    /* Seed from environment (default 42) */
    const char *seed_env = getenv("HEPPH_MICROMEGAS_SEED");
    int seed = seed_env ? atoi(seed_env) : 42;
    srand(seed);

    err = sortOddParticles(pname);
    if (err != 0) {
        fprintf(stderr, "sortOddParticles failed: %d\n", err);
        return 1;
    }

    /* Indirect detection spectra */
    double Emin = 1.0, Emax = 100.0 / 2.0;
    if (Emax <= Emin) Emax = Emin * 100.0;
    double sigmav_spec;
    double SpA[250], SpE[250], SpP[250], SpNe[250];
    err = calcSpectrum(3 /* gamma+e+pbar */, &Emin, &Emax, &sigmav_spec,
                       SpA, SpE, SpP, SpNe, NULL);
    if (err != 0) {
        fprintf(stderr, "calcSpectrum failed: %d\n", err);
        return 1;
    }
    printf("sigma_v(v=0) = %e cm^3/s\n", sigmav_spec);

    /* Relic (needed for context) */
    double Beps = 1.E-6;
    Omega = darkOmega(&Xf, 1, Beps);
    printf("Omega h^2 = %e\n", Omega);
    printf("Xf= %e\n", Xf);
    return 0;
}
