/* micrOMEGAs driver — generated by hephaestus /micromegas relic
 * DM candidate: S (PDG 9000001)
 * HEPPH_MICROMEGAS_SEED: 42
 * DO NOT EDIT — regenerate via scripts/main_c_template.py
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "micromegas.h"
#include "micromegas_aux.h"
#include "pmodel.h"

int main(int argc, char **argv) {
    char *pname = FILE_NAME;
    int err;
    double Omega, Xf;

    /* Seed from environment (default 42) */
    const char *seed_env = getenv("HEPPH_MICROMEGAS_SEED");
    int seed = seed_env ? atoi(seed_env) : 42;
    srand(seed);

    err = sortOddParticles(pname);
    if (err != 0) {
        fprintf(stderr, "sortOddParticles failed: %d\n", err);
        return 1;
    }

    /* Relic density calculation */
    double Beps = 1.E-6;
    Omega = darkOmega(&Xf, 1, Beps);
    printf("Xf= %e\n", Xf);
    printf("Omega h^2 = %e\n", Omega);
    printf("Planck target: 0.120 +/- 0.0012\n");
    if (Omega > 0 && isfinite(Omega)) {
        double pull = (Omega - 0.12) / 0.0012;
        printf("Pull = %.2f sigma\n", pull);
    }
    return 0;
}
