/* micrOMEGAs driver — generated by hephaestus /micromegas scatter
 * DM candidate: S (PDG 9000001)
 * HEPPH_MICROMEGAS_SEED: 42
 * DO NOT EDIT — regenerate via scripts/main_c_template.py
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "micromegas.h"
#include "micromegas_aux.h"
#include "pmodel.h"

int main(int argc, char **argv) {
    char *pname = FILE_NAME;
    int err;
    double Omega, Xf;

    /* Seed from environment (default 42) */
    const char *seed_env = getenv("HEPPH_MICROMEGAS_SEED");
    int seed = seed_env ? atoi(seed_env) : 42;
    srand(seed);

    err = sortOddParticles(pname);
    if (err != 0) {
        fprintf(stderr, "sortOddParticles failed: %d\n", err);
        return 1;
    }

    /* Direct detection cross-sections */
    double pAsi, nAsi, pAsd, nAsd;
    int pdg_dm = 9000001;
    err = nucleonAmplitudes(pdg_dm, &pAsi, &nAsi, &pAsd, &nAsd);
    if (err != 0) {
        fprintf(stderr, "nucleonAmplitudes failed: %d\n", err);
        return 1;
    }
    /* Convert amplitudes to cross-sections: σ = A² * (μ_N)² / π */
    /* micrOMEGAs returns pAsi etc. as amplitudes in GeV^-2 */
    double mN = 0.938272;  /* nucleon mass GeV */
    double mDM = 100.000000;
    double mu_p = mDM * mN / (mDM + mN);
    double mu_n = mu_p;  /* approximation for proton ≈ neutron */
    double GeVm2_to_cm2 = 3.894e-28;  /* 1 GeV^-2 = 3.894e-28 cm^2 */
    double sig_si_p = pAsi * pAsi * mu_p * mu_p / M_PI * GeVm2_to_cm2;
    double sig_si_n = nAsi * nAsi * mu_n * mu_n / M_PI * GeVm2_to_cm2;
    double sig_sd_p = pAsd * pAsd * 3.0 * mu_p * mu_p / M_PI * GeVm2_to_cm2;
    double sig_sd_n = nAsd * nAsd * 3.0 * mu_n * mu_n / M_PI * GeVm2_to_cm2;
    printf("sigma_SI(p) = %e cm^2\n", sig_si_p);
    printf("sigma_SI(n) = %e cm^2\n", sig_si_n);
    printf("sigma_SD(p) = %e cm^2\n", sig_sd_p);
    printf("sigma_SD(n) = %e cm^2\n", sig_sd_n);
    return 0;
}
