"""Render header section (model name, globals, NameOfStates, LagrangianInput)."""
from ._idioms import model_name


HEADER_TEMPLATE = '''(*
 * {name}.m  —  SARAH model file
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)

Off[General::spell]

Model`Name = "{name}";
Model`NameLaTeX = "{name}";
Model`Authors = "{authors}";
Model`Date = "{date}";'''


GLOBAL_TEMPLATE_DISCRETE = 'Global[[{i}]] = {{Z[{n}], {name}}};'
GLOBAL_TEMPLATE_U1 = 'Global[[{i}]] = {{U[1], {name}}};'

LAGRANGIAN_INPUT = '''NameOfStates = {GaugeES, EWSB};

DEFINITION[GaugeES][LagrangianInput] = {
    {LagHC,   {AddHC -> True}},
    {LagNoHC, {AddHC -> False}}
};'''


def render_header(spec: dict) -> str:
    m = spec['model']
    parts = [HEADER_TEMPLATE.format(
        name=m['name'],
        authors=m.get('authors', ''),
        date=m.get('date', ''),
    )]

    globals_ = spec.get('global_symmetries', [])
    if globals_:
        parts.append('')
        for i, gs in enumerate(globals_, 1):
            t = gs['type']
            if t.startswith('Z('):
                n = t[2:-1]
                parts.append(GLOBAL_TEMPLATE_DISCRETE.format(i=i, n=n, name=gs['name']))
            elif t == 'U(1)':
                parts.append(GLOBAL_TEMPLATE_U1.format(i=i, name=gs['name']))

    parts.append('')
    parts.append(LAGRANGIAN_INPUT)
    return '\n'.join(parts) + '\n'
