"""Render parameters.m."""
from typing import Any, List, Tuple
from ..reserved import RENDERER_ALIASES


HEADER = '''(*
 * parameters.m  —  SARAH parameter definitions
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)
'''

# Field name → SARAH directive name. Order matters for emission.
_FIELD_ORDER = [
    ('description', 'Description', 'string'),
    ('latex', 'LaTeX', 'string'),
    ('output_name', 'OutputName', 'symbol'),
    ('real', 'Real', 'bool'),
    ('les_houches', 'LesHouches', 'les_houches'),
    ('dependence_num', 'DependenceNum', 'verbatim'),
    ('dependence', 'Dependence', 'verbatim'),
    ('dependence_spheno', 'DependenceSPheno', 'verbatim'),
]


def render_parameters_m(spec: dict) -> str:
    parts = [HEADER, 'ParameterDefinitions = {', '']

    entries: List[str] = []
    for p in spec.get('parameters', []):
        entries.append(_render_param(p))

    # Join entries with `,\n\n`, then close
    parts.append(',\n\n'.join(entries))
    parts.append('')
    parts.append(' };')

    return '\n'.join(parts) + '\n'


def _render_param(p: dict) -> str:
    name = RENDERER_ALIASES.get(p['name'], p['name'])
    fields: List[Tuple[str, str]] = []
    for key, sarah_key, kind in _FIELD_ORDER:
        if key not in p:
            continue
        val = p[key]
        rendered = _render_value(val, kind)
        if rendered is None:
            continue
        fields.append((sarah_key, rendered))

    if not fields:
        return f'{{{name},  {{ }}}}'   # empty body — unusual but valid

    if len(fields) == 1:
        sarah_key, val = fields[0]
        return f'{{{name},  {{ {sarah_key} -> {val}}}}}'

    # Multiple fields: format on multiple lines
    body_lines = [f'{sarah_key} -> {val}' for sarah_key, val in fields]
    indent = ' ' * (len(name) + 5)
    body = (',\n' + indent).join(body_lines)
    return f'{{{name},  {{ {body} }}}}'


def _render_value(val: Any, kind: str) -> 'str | None':
    if kind == 'string':
        return f'"{val}"'
    if kind == 'symbol':
        return str(val)
    if kind == 'bool':
        return 'True' if val else 'False'
    if kind == 'verbatim':
        return str(val)
    if kind == 'les_houches':
        if isinstance(val, str):
            return val   # bare symbol like ZNMIX
        if isinstance(val, list):
            assert len(val) == 2, f'les_houches list must be 2-tuple, got {val!r}'
            return f'{{{val[0]}, {val[1]}}}'
    return None
