"""Render particles.m."""
from typing import Any, Dict, List, Optional, Tuple
from ..cwt import build_cwt, FieldRef


HEADER = '''(*
 * particles.m  —  SARAH particle content
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)
'''

# Field name → (SARAH directive name, render kind). Order matters for emission.
_FIELD_ORDER: List[Tuple[str, str, str]] = [
    ('description', 'Description', 'string'),
    ('pdg', 'PDG', 'pdg'),
    ('pdg_ix', 'PDG.IX', 'pdg'),
    ('width', 'Width', 'mass_width'),
    ('mass', 'Mass', 'mass_width'),
    ('feynarts_nr', 'FeynArtsNr', 'int'),
    ('latex', 'LaTeX', 'latex_or_string'),
    ('output_name', 'OutputName', 'latex_or_string'),
    ('electric_charge', 'ElectricCharge', 'verbatim'),
    ('goldstone', 'Goldstone', 'symbol'),
]

# Well-known SARAH gauge boson description overrides.
# Key: gauge-group symbol → (boson description, ghost description)
_GAUGE_DESCRIPTIONS: Dict[str, Tuple[str, str]] = {
    'B':   ('B-Boson',  'B-Boson Ghost'),
    'WB':  ('W-Bosons', 'W-Boson Ghost'),
    'G':   ('Gluon',    'Gluon Ghost'),
}


def render_particles_m(spec: dict) -> str:
    parts = [HEADER, '']
    gauge_es = _render_block('ParticleDefinitions[GaugeES]', _gauge_es_entries(spec))
    if gauge_es:
        parts.append(gauge_es)
        parts.append('')
    ewsb = _render_block('ParticleDefinitions[EWSB]', _ewsb_entries(spec))
    if ewsb:
        parts.append(ewsb)
        parts.append('')
    weyl = _render_block('WeylFermionAndIndermediate', _weyl_entries(spec))
    if weyl:
        parts.append(weyl)
        parts.append('')
    return '\n'.join(parts).rstrip('\n') + '\n'


def _gauge_es_entries(spec: dict) -> List[dict]:
    """Auto-emit + user override for GaugeES."""
    by_name: Dict[str, dict] = {}
    order: List[str] = []

    def _add(name: str, entry: dict) -> None:
        if name not in by_name:
            order.append(name)
        by_name[name] = entry

    # Auto-emit scalar components first (they appear first in the golden)
    for s in spec.get('scalars', []):
        comps = s.get('components', [])
        if isinstance(comps, str):
            comps = [comps]
        for comp in comps:
            _add(comp, {
                'name': comp,
                'pdg': [0],
                'width': 0,
                'mass': 'Automatic',
                'latex': comp,
                'output_name': comp,
            })

    # Auto-emit gauge bosons + ghosts
    for g in spec.get('gauge_groups', []):
        sym = g['symbol']
        boson = g.get('boson_name', f'V{sym}')
        ghost = g.get('ghost_name', f'g{sym}')

        # Prefer known SARAH descriptions; fall back to label-derived
        if sym in _GAUGE_DESCRIPTIONS:
            boson_desc, ghost_desc = _GAUGE_DESCRIPTIONS[sym]
        else:
            label = g.get('label', sym)
            boson_desc = f'{label.title()}-Boson'
            ghost_desc = f'{label.title()}-Boson Ghost'

        _add(boson, {'name': boson, 'description': boson_desc})
        _add(ghost, {'name': ghost, 'description': ghost_desc})

    # Auto-emit pre-EWSB Dirac spinor names
    for sp in spec.get('ewsb', {}).get('dirac_spinors_pre_ewsb', []) or []:
        n = sp['name']
        _add(n, {
            'name': n,
            'pdg': [0],
            'width': 0,
            'mass': 'Automatic',
            'latex': n,
            'output_name': n,
        })

    # User overrides (override any auto-default for same name)
    for p in spec.get('particles', {}).get('gauge_es', []) or []:
        name = p['name']
        if name not in by_name:
            order.append(name)
        by_name[name] = p

    return [by_name[n] for n in order]


def _ewsb_entries(spec: dict) -> List[dict]:
    """EWSB: user-declared only."""
    return list(spec.get('particles', {}).get('ewsb', []) or [])


def _weyl_entries(spec: dict) -> List[dict]:
    """Auto-emit Weyl components from CWT, plus user overrides."""
    by_name: Dict[str, dict] = {}
    order: List[str] = []
    cwt = build_cwt(spec)

    # Builtin gauge symbols to skip
    builtin_gauge = {'VB', 'VWB', 'VWp', 'VG', 'VP', 'VZ'}
    # Also skip parameter names
    param_names = {p['name'] for p in spec.get('parameters', [])}

    for sym in cwt:
        if '[' in sym:
            continue   # skip indexed forms; emit only bare component / field
        if sym in builtin_gauge:
            continue
        if sym in param_names:
            continue
        if sym not in by_name:
            order.append(sym)
            by_name[sym] = {'name': sym, 'latex': sym}

    # User overrides
    for p in spec.get('particles', {}).get('weyl_intermediate', []) or []:
        name = p['name']
        if name not in by_name:
            order.append(name)
        by_name[name] = p

    return [by_name[n] for n in order]


def _render_block(header: str, entries: List[dict]) -> str:
    if not entries:
        return ''
    rendered = [_render_entry(e) for e in entries]
    body = ',\n\n'.join(rendered)
    return f'{header} = {{\n\n{body}\n\n}};'


def _render_entry(p: dict) -> str:
    name = p['name']
    fields: List[Tuple[str, str]] = []
    for key, sarah_key, kind in _FIELD_ORDER:
        if key not in p:
            continue
        rendered = _render_value(p[key], kind)
        if rendered is None:
            continue
        fields.append((sarah_key, rendered))

    if not fields:
        return f'{{{name},  {{ }}}}'
    if len(fields) == 1:
        sk, v = fields[0]
        return f'{{{name},  {{ {sk} -> {v}}}}}'
    indent = ' ' * (len(name) + 5)
    lines = [f'{sk} -> {v}' for sk, v in fields]
    body = (',\n' + indent).join(lines)
    return f'{{{name},  {{ {body} }}}}'


def _render_value(val: Any, kind: str) -> Optional[str]:
    if kind == 'string':
        return f'"{val}"'
    if kind == 'symbol':
        return str(val)
    if kind == 'verbatim':
        return str(val)
    if kind == 'int':
        return str(val)
    if kind == 'latex_or_string':
        # Can be a string or a list of strings
        if isinstance(val, list):
            inner = ', '.join(f'"{v}"' for v in val)
            return '{' + inner + '}'
        return f'"{val}"'
    if kind == 'pdg':
        if isinstance(val, list):
            return '{' + ', '.join(str(x) for x in val) + '}'
        return str(val)
    if kind == 'mass_width':
        if val == 'Automatic' or val == 'LesHouches':
            return val   # bare symbol
        if isinstance(val, int):
            return str(val)   # plain int (e.g. 0) renders as-is, not {0}
        if isinstance(val, list):
            return '{' + ', '.join(str(x) for x in val) + '}'
        return str(val)
    return None
