c------------------------------------------------------------------------------c
c This file contains the needed information about all the DM particles.
c------------------------------------------------------------------------------c

      MDM( 1 ) = ABS( MDL_MCHI1 )
      DOF_DM( 1 ) = 2.0
      DM_SM_SCATTERING( 1 ) = .FALSE.
      DM_NAMES( 1 ) ='chi1'
      DM_INDEX( 1 ) = 4
      DM_ANTINAMES( 1 ) = 'chi1'
      DM_ANTIINDEX( 1 ) = 4

c------------------------------------------------------------------------------c
