"""
test_patch_paramcard.py — unit tests for the 2HDM+a param_card patcher.

Covers:
  - PHASES[1] set to 1.0 (the root-cause DM-coupling fix)
  - IMPHASES[1] set to 0.0
  - Tightened regex: single-index _set_block_value must NOT clobber a 2-index row
    whose first element happens to match (e.g. "1 2 val" must survive when patching
    index (1,))
  - Multi-index _set_block_value (UDLMIX 1 1 → 1.0) does NOT touch row "1 2"
  - Idempotency: two consecutive patcher calls produce identical output
  - Untouched blocks: SMINPUTS alpha_em entry is bytewise unchanged
"""

import re
import sys
import tempfile
from pathlib import Path

# Make sure the scripts/ directory is importable.
SKILL_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SKILL_DIR / "scripts"))

from patch_paramcard import _set_block_value, patch_paramcard  # noqa: E402

# ---------------------------------------------------------------------------
# Realistic param_card fixture (embedded as a string)
# ---------------------------------------------------------------------------

PARAM_CARD_FIXTURE = """\
######################################################################
## PARAM_CARD GENERATED BY MADDM
######################################################################

Block SMINPUTS
    1  1.31667e+02   # aEWM1 (alpha_em inverse)
    2  1.16638e-05   # Gf
    3  1.18400e-01   # aS

Block MASS
    25  1.25000e+02   # hh1 (SM-like Higgs)
    9931569  4.00000e+02   # Ah2 (DM pseudoscalar mediator)
    9989932  1.00000e+02   # Fchi (DM)

Block PHASES
    1  0.00000e+00   # rpchiR (BROKEN — zero kills DM coupling)

Block IMPHASES
    1  0.00000e+00   # ipchiR

Block HMIX
    102  2.45000e+01   # vd
    103  2.44000e+02   # vu

Block UDLMIX
    1 1  1.00000e+00   # (1,1)
    1 2  0.00000e+00   # (1,2) must NOT be touched by single-index patch
    1 3  0.00000e+00   # (1,3)
    2 1  0.00000e+00   # (2,1)
    2 2  1.00000e+00   # (2,2)
    2 3  0.00000e+00   # (2,3)
    3 1  0.00000e+00   # (3,1)
    3 2  0.00000e+00   # (3,2)
    3 3  1.00000e+00   # (3,3)

"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _write_card(tmp_dir: Path, text: str) -> Path:
    """Write a Cards/param_card.dat into tmp_dir and return its path."""
    cards = tmp_dir / "Cards"
    cards.mkdir(parents=True, exist_ok=True)
    card_path = cards / "param_card.dat"
    card_path.write_text(text)
    return card_path


def _get_block_value(text: str, block: str, index: tuple) -> float:
    """
    Minimal inline parser: find the first line inside BLOCK <block> whose
    leading integer tokens match *index exactly* and return its float value.
    Raises AssertionError if not found.
    """
    in_block = False
    idx_ints = list(index)
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("block "):
            in_block = stripped.split()[1].upper() == block.upper()
            continue
        if stripped.lower().startswith("decay"):
            in_block = False
            continue
        if not in_block or not stripped or stripped.startswith("#"):
            continue
        parts = stripped.split()
        leading = []
        for p in parts:
            try:
                leading.append(int(p))
            except ValueError:
                break
        if leading == idx_ints and len(parts) > len(idx_ints):
            return float(parts[len(idx_ints)])
    raise AssertionError(f"Block {block} index {index} not found in card text")


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_phases_set_to_one():
    """PHASES[1] must be 1.0 after patching (root-cause fix)."""
    with tempfile.TemporaryDirectory() as tmp:
        run_dir = Path(tmp)
        _write_card(run_dir, PARAM_CARD_FIXTURE)
        patch_paramcard(run_dir)
        result = (run_dir / "Cards" / "param_card.dat").read_text()
        assert _get_block_value(result, "PHASES", (1,)) == 1.0, (
            "PHASES[1] should be 1.0 to restore DM couplings"
        )


def test_imphases_set_to_zero():
    """IMPHASES[1] must be 0.0 after patching (imaginary part stays zero)."""
    with tempfile.TemporaryDirectory() as tmp:
        run_dir = Path(tmp)
        _write_card(run_dir, PARAM_CARD_FIXTURE)
        patch_paramcard(run_dir)
        result = (run_dir / "Cards" / "param_card.dat").read_text()
        assert _get_block_value(result, "IMPHASES", (1,)) == 0.0, (
            "IMPHASES[1] should be 0.0 (pure-real phase)"
        )


def test_single_index_does_not_clobber_two_index_row():
    """
    _set_block_value(lines, "UDLMIX", (1,), 99.0) must NOT overwrite the
    "1 2  0.0" row — the tightened regex (?!\\d) prevents this collision.
    """
    lines = PARAM_CARD_FIXTURE.splitlines(keepends=True)
    # Attempt to set a single-index (1,) entry in UDLMIX
    modified = _set_block_value(lines[:], "UDLMIX", (1,), 99.0, "probe")
    text = "".join(modified)
    # The 1 2 row in UDLMIX must be untouched
    val_1_2 = _get_block_value(text, "UDLMIX", (1, 2))
    assert val_1_2 == 0.0, (
        f"UDLMIX (1,2) was corrupted by single-index patch: got {val_1_2}"
    )


def test_two_index_patch_does_not_touch_adjacent_row():
    """
    _set_block_value(lines, "UDLMIX", (1, 1), 1.0) must NOT modify row (1, 2).
    """
    lines = PARAM_CARD_FIXTURE.splitlines(keepends=True)
    modified = _set_block_value(lines[:], "UDLMIX", (1, 1), 1.0, "identity")
    text = "".join(modified)
    val_1_2 = _get_block_value(text, "UDLMIX", (1, 2))
    assert val_1_2 == 0.0, (
        f"UDLMIX (1,2) corrupted when patching (1,1): got {val_1_2}"
    )


def test_idempotency():
    """Running the patcher twice produces identical output to a single run."""
    with tempfile.TemporaryDirectory() as tmp:
        run_dir = Path(tmp)
        _write_card(run_dir, PARAM_CARD_FIXTURE)
        patch_paramcard(run_dir)
        after_one = (run_dir / "Cards" / "param_card.dat").read_text()
        patch_paramcard(run_dir)
        after_two = (run_dir / "Cards" / "param_card.dat").read_text()
        assert after_one == after_two, (
            "patch_paramcard is not idempotent: second run changed the card"
        )


def test_untouched_block_unchanged():
    """
    SMINPUTS block must be bytewise unchanged after patching.
    Specifically, the alpha_em inverse row (1  1.31667e+02) must survive intact.
    """
    with tempfile.TemporaryDirectory() as tmp:
        run_dir = Path(tmp)
        _write_card(run_dir, PARAM_CARD_FIXTURE)
        patch_paramcard(run_dir)
        result = (run_dir / "Cards" / "param_card.dat").read_text()
        aew_val = _get_block_value(result, "SMINPUTS", (1,))
        assert abs(aew_val - 1.31667e+02) < 1e-3, (
            f"SMINPUTS[1] (alpha_em inverse) was modified: got {aew_val}"
        )
