"""
test_patch_paramcard_insert.py — regression tests for the T2 insert-path fix in
plugins/hep-ph-toolkit/skills/2hdm-a/scripts/patch_paramcard.py

Covers (per PLAN_FINAL T3 spec + T2_REVIEW_c1 independent cases):

  [T3-1] single-space SLHA replace — original bug case (single space between
         index and value; the old (?!\\d) regex rejected this)
  [T3-2] double-space SLHA replace — regression (double space, must also work)
  [T3-3] multi-index (1,1) vs (1,) vs (1,2) disambiguation — case C from review
  [T3-4] scientific-notation value — case D from review (1e-12 → 2.5e-9)
  [T3-5] case-insensitive block header — case G from review (lowercase "block dmsector")
  [T3-6] comment-line skip — case H from review (comment before data row is ignored)
  [T3-7] create-block-tail: DMSECTOR absent → header + indexed line created — case E
  [T3-8] insert into header-only block (PHASES exists but empty) — case F from review
  [T3-9] full-patcher DMSECTOR/PHASES/ZAMIX on minimal fresh card — the T3 integration
         assertion from PLAN_FINAL (blocks present AND each has ≥1 indexed line)
"""

import re
import sys
import tempfile
from pathlib import Path

# ---------------------------------------------------------------------------
# Import the module under test.  patch_paramcard.py lives in ../scripts/.
# ---------------------------------------------------------------------------
SKILL_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SKILL_DIR / "scripts"))

from patch_paramcard import _set_block_value, patch_paramcard  # noqa: E402

# ---------------------------------------------------------------------------
# Minimal fresh MG5 param_card: only MASS and SMINPUTS — DMSECTOR/PHASES/ZAMIX
# are intentionally ABSENT.  This is the failing-case card from the T2 diagnosis.
# ---------------------------------------------------------------------------

FRESH_CARD = """\
######################################################################
## PARAM_CARD GENERATED BY MADDM (fresh output, minimal)
######################################################################

Block SMINPUTS
    1  1.31667e+02   # aEWM1 (alpha_em inverse)
    2  1.16638e-05   # Gf
    3  1.18400e-01   # aS

Block MASS
    25  1.25000e+02   # hh1 (SM-like Higgs)
    9931569  4.00000e+02   # Ah2

"""

# ---------------------------------------------------------------------------
# Minimal card that HAS the blocks but they are header-only (no entries).
# Used to test insert-into-existing-but-empty-block path (scan-2).
# ---------------------------------------------------------------------------

HEADER_ONLY_CARD = """\
Block MASS
    25  1.25000e+02   # hh1

Block PHASES

Block SMINPUTS
    1  1.31667e+02   # aEWM1

"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_lines(text: str):
    """Return a list of lines (with line endings) from a card string."""
    return text.splitlines(keepends=True)


def _make_run_dir(tmp_dir: str, card_text: str) -> Path:
    """Write card_text into <tmp_dir>/Cards/param_card.dat; return Path(tmp_dir)."""
    run_dir = Path(tmp_dir)
    cards = run_dir / "Cards"
    cards.mkdir(parents=True, exist_ok=True)
    (cards / "param_card.dat").write_text(card_text)
    return run_dir


def _block_entries(text: str, block: str):
    """
    Return all indexed lines (leading integers + float value) inside the named
    block as a list of (tuple_of_ints, float) pairs.
    Stops at the next Block/Decay header or EOF.
    """
    entries = []
    in_block = False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("block "):
            in_block = stripped.split()[1].upper() == block.upper()
            continue
        if stripped.lower().startswith("decay"):
            in_block = False
            continue
        if not in_block or not stripped or stripped.startswith("#"):
            continue
        parts = stripped.split()
        idx = []
        for p in parts:
            try:
                idx.append(int(p))
            except ValueError:
                break
        if idx and len(parts) > len(idx):
            try:
                val = float(parts[len(idx)])
                entries.append((tuple(idx), val))
            except ValueError:
                pass
    return entries


def _get_value(text: str, block: str, index: tuple) -> float:
    """Return the float value for the given block/index; raise AssertionError if absent."""
    for idx_tuple, val in _block_entries(text, block):
        if idx_tuple == index:
            return val
    raise AssertionError(f"Block {block} index {index} not found")


# ---------------------------------------------------------------------------
# [T3-1] Single-space SLHA replace — the original bug case
# ---------------------------------------------------------------------------

def test_single_space_slha_replace():
    """
    Card uses single space between index and value: '   1 0.000000e+00'.
    After _set_block_value(..., "DMSECTOR", (1,), 100.0) the index (1,) must
    hold 100.0, not be duplicated or left at 0.0.
    """
    card = (
        "Block MASS\n"
        "    1  1.25000e+02   # hh1\n"
        "\n"
        "Block DMSECTOR\n"
        "   1 0.000000e+00   # mchi (single-space)\n"
    )
    lines = _make_lines(card)
    result = _set_block_value(lines[:], "DMSECTOR", (1,), 100.0, "mchi")
    text = "".join(result)
    val = _get_value(text, "DMSECTOR", (1,))
    assert abs(val - 100.0) < 1e-9, f"[T3-1] DMSECTOR(1,) should be 100.0, got {val}"
    # No duplicate: exactly one indexed line in DMSECTOR
    entries = _block_entries(text, "DMSECTOR")
    assert len(entries) == 1, f"[T3-1] Expected 1 entry in DMSECTOR, found {len(entries)}: {entries}"


# ---------------------------------------------------------------------------
# [T3-2] Double-space SLHA replace — regression
# ---------------------------------------------------------------------------

def test_double_space_slha_replace():
    """
    Card uses double space: '   1  0.000000e+00'.
    Must replace cleanly without duplication.
    """
    card = (
        "Block MASS\n"
        "    1  1.25000e+02   # hh1\n"
        "\n"
        "Block DMSECTOR\n"
        "   1  0.000000e+00   # mchi (double-space)\n"
    )
    lines = _make_lines(card)
    result = _set_block_value(lines[:], "DMSECTOR", (1,), 100.0, "mchi")
    text = "".join(result)
    val = _get_value(text, "DMSECTOR", (1,))
    assert abs(val - 100.0) < 1e-9, f"[T3-2] DMSECTOR(1,) should be 100.0, got {val}"
    entries = _block_entries(text, "DMSECTOR")
    assert len(entries) == 1, f"[T3-2] Expected 1 entry in DMSECTOR, found {len(entries)}: {entries}"


# ---------------------------------------------------------------------------
# [T3-3] Multi-index disambiguation: (1,1) vs (1,) vs (1,2)
# ---------------------------------------------------------------------------

def test_multi_index_disambiguation():
    """
    Block with rows (1,1), (1,2), (2,1).  Patching (1,1) → 0.5 must not
    touch (1,2) or (2,1).  Directly exercises the structural key lookup.
    """
    card = (
        "Block ZAMIX\n"
        "   1 1  0.000000e+00   # ZA(1,1)\n"
        "   1 2  0.000000e+00   # ZA(1,2)\n"
        "   2 1  0.000000e+00   # ZA(2,1)\n"
    )
    lines = _make_lines(card)
    result = _set_block_value(lines[:], "ZAMIX", (1, 1), 0.5)
    text = "".join(result)
    assert abs(_get_value(text, "ZAMIX", (1, 1)) - 0.5) < 1e-9, "[T3-3] (1,1) not updated"
    assert abs(_get_value(text, "ZAMIX", (1, 2)) - 0.0) < 1e-9, "[T3-3] (1,2) was corrupted"
    assert abs(_get_value(text, "ZAMIX", (2, 1)) - 0.0) < 1e-9, "[T3-3] (2,1) was corrupted"
    # Also verify single-index (1,) would not match any of the above
    result2 = _set_block_value(lines[:], "ZAMIX", (1,), 99.0)
    text2 = "".join(result2)
    # (1,1) and (1,2) must both be untouched (they are 2-index rows)
    assert abs(_get_value(text2, "ZAMIX", (1, 1)) - 0.0) < 1e-9, "[T3-3] (1,1) corrupted by (1,) patch"
    assert abs(_get_value(text2, "ZAMIX", (1, 2)) - 0.0) < 1e-9, "[T3-3] (1,2) corrupted by (1,) patch"


# ---------------------------------------------------------------------------
# [T3-4] Scientific-notation value
# ---------------------------------------------------------------------------

def test_scientific_notation_value():
    """
    Replace a value given in scientific notation (1.000000e-12) with 2.5e-9.
    The _parse_block_structure float() parse must handle both source and target.
    """
    card = (
        "Block DMSECTOR\n"
        "   3  1.000000e-12   # tiny coupling\n"
    )
    lines = _make_lines(card)
    result = _set_block_value(lines[:], "DMSECTOR", (3,), 2.5e-9, "coupling")
    text = "".join(result)
    val = _get_value(text, "DMSECTOR", (3,))
    assert abs(val - 2.5e-9) < 1e-18, f"[T3-4] Expected 2.5e-9, got {val}"
    entries = _block_entries(text, "DMSECTOR")
    assert len(entries) == 1, f"[T3-4] No duplicate expected, found {len(entries)}: {entries}"


# ---------------------------------------------------------------------------
# [T3-5] Case-insensitive block header
# ---------------------------------------------------------------------------

def test_case_insensitive_block_header():
    """
    Block header written as 'block dmsector' (all lowercase) must be matched
    case-insensitively and its value replaced correctly.
    """
    card = (
        "block dmsector\n"
        "   1  0.000000e+00   # mchi\n"
    )
    lines = _make_lines(card)
    result = _set_block_value(lines[:], "DMSECTOR", (1,), 100.0)
    text = "".join(result)
    val = _get_value(text, "DMSECTOR", (1,))
    assert abs(val - 100.0) < 1e-9, f"[T3-5] Expected 100.0, got {val}"


# ---------------------------------------------------------------------------
# [T3-6] Comment-line skip
# ---------------------------------------------------------------------------

def test_comment_line_skip():
    """
    A comment line inside the block (before the data row) must not prevent the
    data row from being found and replaced.
    """
    card = (
        "Block DMSECTOR\n"
        "# This is a comment inside the block\n"
        "   1  0.000000e+00   # mchi\n"
    )
    lines = _make_lines(card)
    result = _set_block_value(lines[:], "DMSECTOR", (1,), 100.0)
    text = "".join(result)
    val = _get_value(text, "DMSECTOR", (1,))
    assert abs(val - 100.0) < 1e-9, f"[T3-6] Expected 100.0, got {val}"
    entries = _block_entries(text, "DMSECTOR")
    assert len(entries) == 1, f"[T3-6] Duplicate entry found: {entries}"


# ---------------------------------------------------------------------------
# [T3-7] create-block-tail: DMSECTOR absent → appended at EOF
# ---------------------------------------------------------------------------

def test_create_block_tail_when_block_absent():
    """
    Card has no DMSECTOR block at all.  After _set_block_value(..., "DMSECTOR",
    (1,), 100.0) the result must contain a 'Block DMSECTOR' header followed by
    an indexed line with value 100.0 at EOF.
    """
    card = (
        "Block MASS\n"
        "    1  1.25000e+02   # hh1\n"
        "\n"
        "Block SMINPUTS\n"
        "    1  1.31667e+02   # aEWM1\n"
    )
    lines = _make_lines(card)
    result = _set_block_value(lines[:], "DMSECTOR", (1,), 100.0, "mchi")
    text = "".join(result)
    # Block header must appear
    assert re.search(r"^Block DMSECTOR\s*$", text, re.M | re.I), \
        "[T3-7] 'Block DMSECTOR' header not found after create-block-tail"
    # Indexed line must appear
    val = _get_value(text, "DMSECTOR", (1,))
    assert abs(val - 100.0) < 1e-9, f"[T3-7] Expected 100.0 in new DMSECTOR block, got {val}"


# ---------------------------------------------------------------------------
# [T3-8] Insert into header-only block (scan-2 path)
# ---------------------------------------------------------------------------

def test_insert_into_header_only_block():
    """
    PHASES block header exists but has no entries.  After _set_block_value(
    ..., "PHASES", (1,), 1.0) the value must appear between the PHASES header
    and the next Block/EOF, not appended to EOF as a new block.
    """
    lines = _make_lines(HEADER_ONLY_CARD)
    result = _set_block_value(lines[:], "PHASES", (1,), 1.0, "rpchiR")
    text = "".join(result)
    val = _get_value(text, "PHASES", (1,))
    assert abs(val - 1.0) < 1e-9, f"[T3-8] Expected 1.0 in PHASES, got {val}"
    # Only one PHASES block header (not a second one appended at EOF)
    headers = re.findall(r"^Block PHASES\s*$", text, re.M | re.I)
    assert len(headers) == 1, f"[T3-8] More than one Block PHASES header found: {headers}"


# ---------------------------------------------------------------------------
# [T3-9] Full-patcher integration: DMSECTOR/PHASES/ZAMIX on fresh MG5 card
# ---------------------------------------------------------------------------

def test_full_patcher_fresh_card_dmsector_phases_zamix():
    """
    Run patch_paramcard() on a minimal fresh card that has ONLY Block MASS and
    Block SMINPUTS (DMSECTOR/PHASES/ZAMIX are absent — the original T1 finding).

    Asserts (per PLAN_FINAL T3 spec):
      1. re.search(r'^Block DMSECTOR\\s*$', text, re.M | re.I) is truthy.
      2. re.search(r'^Block PHASES\\s*$', text, re.M | re.I) is truthy.
      3. re.search(r'^Block ZAMIX\\s*$', text, re.M | re.I) is truthy.
      4. For each of the three blocks, at least one indexed line exists between
         the block header and the next ^Block /^Decay /EOF.
    """
    with tempfile.TemporaryDirectory() as tmp:
        run_dir = _make_run_dir(tmp, FRESH_CARD)
        patch_paramcard(run_dir)
        text = (run_dir / "Cards" / "param_card.dat").read_text()

    # 1-3: block headers present
    assert re.search(r"^Block DMSECTOR\s*$", text, re.M | re.I), \
        "[T3-9] Block DMSECTOR header absent after full patch on fresh card"
    assert re.search(r"^Block PHASES\s*$", text, re.M | re.I), \
        "[T3-9] Block PHASES header absent after full patch on fresh card"
    assert re.search(r"^Block ZAMIX\s*$", text, re.M | re.I), \
        "[T3-9] Block ZAMIX header absent after full patch on fresh card"

    # 4: each block has ≥1 indexed line beneath its header
    indexed_line_re = re.compile(r"^\s+\d+(\s+\d+)*\s+[-+0-9.eE]+")
    for block_name in ("DMSECTOR", "PHASES", "ZAMIX"):
        entries = _block_entries(text, block_name)
        assert len(entries) >= 1, \
            f"[T3-9] Block {block_name} has no indexed entries after full patch"

    # Spot-check: PHASES[1] must be 1.0 (the root-cause DM-coupling fix)
    phases_val = _get_value(text, "PHASES", (1,))
    assert abs(phases_val - 1.0) < 1e-9, \
        f"[T3-9] PHASES[1] = {phases_val}, expected 1.0 (PhasechiR fix)"

    # Spot-check: DMSECTOR[1] = 100.0 (default Mchi)
    dmsector_val = _get_value(text, "DMSECTOR", (1,))
    assert abs(dmsector_val - 100.0) < 1e-9, \
        f"[T3-9] DMSECTOR[1] = {dmsector_val}, expected 100.0 (default Mchi)"


# ---------------------------------------------------------------------------
# [T3-10] PDG 37 (MHm1=Mw=80.419) insert into MASS block — T2-c2 regression
# ---------------------------------------------------------------------------

def test_pdg37_insert_into_mass_block_when_absent():
    """
    Fresh card has NO PDG 37 line in Block MASS.  After _set_block_value(
    ..., "MASS", (37,), 80.419, "MHm1 ~ Mw") the result must have exactly
    one MASS entry with index (37,) equal to 80.419.

    Regression for T2-c2 fix (D8): T2 patcher previously omitted PDG 37,
    causing Ωh² = 22.3 instead of the PT1 reference value ~10.494.
    """
    # Card with MASS block but no PDG 37 row
    card = (
        "Block MASS\n"
        "   25  1.250000e+02   # hh1 (SM-like Higgs)\n"
        "   9931569  4.000000e+02   # Ah2\n"
    )
    lines = _make_lines(card)
    result = _set_block_value(lines[:], "MASS", (37,), 80.419, "MHm1 ~ Mw")
    text = "".join(result)
    val = _get_value(text, "MASS", (37,))
    assert abs(val - 80.419) < 1e-6, f"[T3-10] MASS(37,) should be 80.419 (Mw), got {val}"
    # No duplicate PDG 37 entries
    entries_37 = [(idx, v) for idx, v in _block_entries(text, "MASS") if idx == (37,)]
    assert len(entries_37) == 1, f"[T3-10] Expected 1 MASS entry for PDG 37, found {len(entries_37)}: {entries_37}"
    # Confirm formatted line is present (standard SLHA format)
    assert re.search(r"^\s+37\s+8\.041900e\+01", text, re.M), \
        "[T3-10] MASS PDG 37 line not formatted as expected (   37  8.041900e+01)"


def test_pdg37_update_existing_mass_entry():
    """
    Card already has PDG 37 in Block MASS at 100.0 GeV (MadDM default).
    After _set_block_value(..., "MASS", (37,), 80.419, "MHm1 ~ Mw") the
    entry must be updated to 80.419 without duplication.

    Verifies the replace-existing-index path of _set_block_value for PDG 37.
    """
    card = (
        "Block MASS\n"
        "   25  1.250000e+02   # hh1\n"
        "   37  1.000000e+02   # MHm1 (model default)\n"
        "   9931569  4.000000e+02   # Ah2\n"
    )
    lines = _make_lines(card)
    result = _set_block_value(lines[:], "MASS", (37,), 80.419, "MHm1 ~ Mw")
    text = "".join(result)
    val = _get_value(text, "MASS", (37,))
    assert abs(val - 80.419) < 1e-6, f"[T3-11] MASS(37,) should be 80.419 (Mw), got {val}"
    # No duplicate
    entries_37 = [(idx, v) for idx, v in _block_entries(text, "MASS") if idx == (37,)]
    assert len(entries_37) == 1, f"[T3-11] Expected 1 MASS entry for PDG 37 after update, found {len(entries_37)}: {entries_37}"
    # Old value 100.0 must not remain
    assert not re.search(r"^\s+37\s+1\.000000e\+02", text, re.M), \
        "[T3-11] Old MHm1=100.0 line still present after update to 80.419"


def test_full_patcher_sets_pdg37_mw():
    """
    Full patch_paramcard() on a minimal fresh card must write PDG 37 = 80.419
    under Block MASS.  Verifies the end-to-end patcher path for the T2-c2 fix.
    """
    with tempfile.TemporaryDirectory() as tmp:
        run_dir = _make_run_dir(tmp, FRESH_CARD)
        patch_paramcard(run_dir)
        text = (run_dir / "Cards" / "param_card.dat").read_text()

    val = _get_value(text, "MASS", (37,))
    assert abs(val - 80.419) < 1e-6, \
        f"[T3-12] Full patcher: MASS(37,) should be 80.419 (Mw), got {val}"
    assert re.search(r"^\s+37\s+8\.041900e\+01", text, re.M), \
        "[T3-12] Full patcher: PDG 37 MASS line not in expected SLHA format"
