# SPheno output — clean spectrum (test fixture)
# Generated by: tests/fixtures/slha/clean_spectrum.spc (synthetic)
Block SPINFO
   1   SPheno
   2   4.0.5

Block SMINPUTS
   1   1.279340000E+02
   2   1.166380000E-05
   3   1.184000000E-01
   4   9.118760000E+01
   5   4.180000000E+00
   6   1.734000000E+02
   7   1.776820000E+00

Block MASS
   # PDG code   mass (GeV)
   25            1.250000000E+02   # Higgs
   1000006       1.000000000E+03   # dark fermion singlet psiD
   1000001       5.000000000E+02   # psiDL
   1000002       5.000000000E+02   # psiDR

DECAY 25  4.07000000E-03
   1.000000E+00    2    5   -5   # H -> bb

Block NMIX
   1  1   9.900000000E-01
   1  2   1.400000000E-01
   2  1  -1.400000000E-01
   2  2   9.900000000E-01
