# SPheno output — synthetic recoverable trigger (test fixture)
# This SLHA contains Block PROBLEM code 1, which deterministically triggers
# status=recoverable / blocker_code=SPHENO_SPECTRUM_PROBLEM in scan.py.
# Used by test_recoverable_handling.py and test_scan_recoverable_row.py.
# NOT generated by real SPheno — hand-crafted for deterministic testing.
Block SPINFO
   1   SPheno
   2   4.0.5

Block SMINPUTS
   1   1.279340000E+02
   2   1.166380000E-05

Block MASS
   1000001   5.000000000E+02

Block PROBLEM
   1   1.00000000E+00   # tachyonic scalar mass squared — triggers SPECTRUM_PROBLEM
