(*
 * <Name>.m  —  SARAH model file
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)

Off[General::spell]

Model`Name = "DarkSU3";
Model`NameLaTeX = "DarkSU3";
Model`Authors = "John Tamanas";
Model`Date = "2026-04-22";

NameOfStates = {GaugeES, EWSB};

DEFINITION[GaugeES][LagrangianInput] = {
    {LagHC,   {AddHC -> True}},
    {LagNoHC, {AddHC -> False}}
};

Gauge[[1]] = {B, U[1], hypercharge, g1, False};
Gauge[[2]] = {WB, SU[2], left, g2, True};
Gauge[[3]] = {G, SU[3], color, g3, False};
Gauge[[4]] = {GD, SU[3], dark, gD, False};

FermionFields[[1]] = {q, 3, {uL, dL},  1/6, 2,  3, 1};
FermionFields[[2]] = {LL, 3, {vL, eL}, -1/2, 2,  1, 1};
FermionFields[[3]] = {d, 3, conj[dR],    1/3, 1, -3, 1};
FermionFields[[4]] = {u, 3, conj[uR],   -2/3, 1, -3, 1};
FermionFields[[5]] = {e, 3, conj[eR],      1, 1,  1, 1};

FermionFields[[6]] = {psiDL, 1, psiDL, 0, 1, 1, 3};
FermionFields[[7]] = {psiDR, 1, conj[psiDR], 0, 1, 1, 3};

ScalarFields[[1]] = {H, 1, {Hp, H0},  1/2, 2,  1, 1};

LagNoHC = -mu2 conj[H].H -1/2 \[Lambda] conj[H].H.conj[H].H;

LagHC = -(Yd conj[H].d.q + Ye conj[H].e.LL -Yu H.u.q + MpsiD psiDL.psiDR);

DEFINITION[EWSB][MatterSector] = {
  {{{dL}, {conj[dR]}}, {{DL, Vd}, {DR, Ud}}},
  {{{uL}, {conj[uR]}}, {{UL, Vu}, {UR, Uu}}},
  {{{eL}, {conj[eR]}}, {{EL, Ve}, {ER, Ue}}}
};

DEFINITION[GaugeES][DiracSpinors] = {
  Fd1 -> {dL, 0},
  Fd2 -> {0, dR},
  Fu1 -> {uL, 0},
  Fu2 -> {0, uR},
  Fe1 -> {eL, 0},
  Fe2 -> {0, eR},
  Fv1 -> {vL, 0},
  FpsiDL0 -> {psiDL, 0},
  FpsiDR0 -> {0, psiDR}
};

DEFINITION[EWSB][GaugeSector] = {
  {{VB, VWB[3]}, {VP, VZ}, ZZ},
  {{VWB[1], VWB[2]}, {VWp, conj[VWp]}, ZW}
};

DEFINITION[EWSB][VEVs] = {
  {H0, {v, 1/Sqrt[2]}, {Ah, \[ImaginaryI]/Sqrt[2]}, {hh, 1/Sqrt[2]}}
};

DEFINITION[EWSB][Phases] = {};

DEFINITION[EWSB][DiracSpinors] = {
  Fd  -> {DL,  conj[DR]},
  Fe  -> {EL,  conj[ER]},
  Fu  -> {UL,  conj[UR]},
  Fv  -> {vL,  0},
  FpsiD -> {psiDL, conj[psiDR]}
};
