(*
 * SPheno.m  —  SARAH SPheno interface configuration
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)

(* SPheno.m — minimal stub for models without SPheno output.

   This model's spec.outputs does not include "spheno".
   run_sarah.py will NOT dispatch MakeSPheno[] for this model.

   The file exists so the render bar is satisfied (four .m files always
   present in the SARAH model directory).

   Per T05d addenda: no suppression option lines are emitted because they
   would be either no-ops or invalid for our direct-dispatch invocation path.
*)

(* MINPAR would go here for a full SPheno model:
MINPAR = {
{1, <param1>},
{2, <param2>},
...
};
*)
