(*
 * <Name>.m  —  SARAH model file
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)

Off[General::spell]

Model`Name = "2hdmA";
Model`NameLaTeX = "2hdmA";
Model`Authors = "John Tamanas";
Model`Date = "2026-04-24";

NameOfStates = {GaugeES, EWSB};

DEFINITION[GaugeES][LagrangianInput] = {
    {LagHC,   {AddHC -> True}},
    {LagNoHC, {AddHC -> False}}
};

Gauge[[1]] = {B, U[1], hypercharge, g1, False};
Gauge[[2]] = {WB, SU[2], left, g2, True};
Gauge[[3]] = {G, SU[3], color, g3, False};

FermionFields[[1]] = {q, 3, {uL, dL},  1/6, 2,  3};
FermionFields[[2]] = {LL, 3, {vL, eL}, -1/2, 2,  1};
FermionFields[[3]] = {d, 3, conj[dR],    1/3, 1, -3};
FermionFields[[4]] = {u, 3, conj[uR],   -2/3, 1, -3};
FermionFields[[5]] = {e, 3, conj[eR],      1, 1,  1};

FermionFields[[6]] = {ChiL, 1, chiL, 0, 1, 1};
FermionFields[[7]] = {ChiR, 1, conj[chiR], 0, 1, 1};

ScalarFields[[1]] = {H1, 1, {H1p, H10}, 1/2, 2, 1};
ScalarFields[[2]] = {H2, 1, {H2p, H20}, 1/2, 2, 1};
ScalarFields[[3]] = {a0, 1, {a0}, 0, 1, 1};

RealScalars = {a0};

LagNoHC = mu11_sq H1.H1 + mu22_sq H2.H2 + ma_sq a0.a0 + lam1 H1.H1.H1.H1 + lam2 H2.H2.H2.H2 + lam3 H1.H1.H2.H2 + kap_aHH a0.H1.H2;

LagHC = -(mchi ChiR.ChiL + Yu2 H2.u.q + Yd1 H1.d.q + Ye1 H1.e.l + \[ImaginaryI] ychi a0.ChiR.ChiL);

DEFINITION[EWSB][MatterSector] = {
  {{{dL}, {conj[dR]}}, {{DL, Vd}, {DR, Ud}}},
  {{{uL}, {conj[uR]}}, {{UL, Vu}, {UR, Uu}}},
  {{{eL}, {conj[eR]}}, {{EL, Ve}, {ER, Ue}}},
  {{hh1, hh2}, {hh, ZH}},
  {{Ah1, Ah2, a0}, {Ah, ZA}},
  {{conj[H1p], conj[H2p]}, {Hm, ZP}}
};

DEFINITION[GaugeES][DiracSpinors] = {
  Fd1 -> {dL, 0},
  Fd2 -> {0, dR},
  Fu1 -> {uL, 0},
  Fu2 -> {0, uR},
  Fe1 -> {eL, 0},
  Fe2 -> {0, eR},
  Fv1 -> {vL, 0},
  Fchi1 -> {chiL, 0},
  Fchi2 -> {0, chiR}
};

DEFINITION[EWSB][GaugeSector] = {
  {{VB, VWB[3]}, {VP, VZ}, ZZ},
  {{VWB[1], VWB[2]}, {VWp, conj[VWp]}, ZW}
};

DEFINITION[EWSB][VEVs] = {
  {H10, {vd, 1/Sqrt[2]}, {Ah1, \[ImaginaryI]/Sqrt[2]}, {hh1, 1/Sqrt[2]}},
  {H20, {vu, 1/Sqrt[2]}, {Ah2, \[ImaginaryI]/Sqrt[2]}, {hh2, 1/Sqrt[2]}}
};

DEFINITION[EWSB][Phases] = {
  {chiR, PhasechiR}
};

DEFINITION[EWSB][DiracSpinors] = {
  Fd  -> {DL,  conj[DR]},
  Fe  -> {EL,  conj[ER]},
  Fu  -> {UL,  conj[UR]},
  Fv  -> {vL,  0},
  Fchi -> {chiL, chiR}
};
