(*
 * parameters.m  —  SARAH parameter definitions
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)

ParameterDefinitions = {

{g1,        { Description -> "Hypercharge-Coupling"}},
{g2,        { Description -> "Left-Coupling"}},
{g3,        { Description -> "Strong-Coupling"}},
{AlphaS,    { Description -> "Alpha Strong"}},
{e,         { Description -> "electric charge"}},
{Gf,        { Description -> "Fermi's constant"}},
{aEWinv,    { Description -> "inverse weak coupling constant at mZ"}},

{Yu,        { Description -> "Up-Yukawa-Coupling",
              DependenceNum ->  Sqrt[2]/v* {{Mass[Fu,1],0,0},
                                           {0, Mass[Fu,2],0},
                                           {0, 0, Mass[Fu,3]}}  }},
{Yd,        { Description -> "Down-Yukawa-Coupling",
              DependenceNum ->  Sqrt[2]/v* {{Mass[Fd,1],0,0},
                                           {0, Mass[Fd,2],0},
                                           {0, 0, Mass[Fd,3]}}  }},
{Ye,        { Description -> "Lepton-Yukawa-Coupling",
              DependenceNum ->  Sqrt[2]/v* {{Mass[Fe,1],0,0},
                                           {0, Mass[Fe,2],0},
                                           {0, 0, Mass[Fe,3]}}  }},

{ThetaW,    { Description -> "Weinberg-Angle",
              DependenceNum -> ArcSin[Sqrt[1 - Mass[VWp]^2/Mass[VZ]^2]]}},
{ZZ,        { Description -> "Photon-Z Mixing Matrix"}},
{ZW,        { Description -> "W Mixing Matrix",
               Dependence ->   1/Sqrt[2] {{1, 1},
                              {\[ImaginaryI],-\[ImaginaryI]}} }},

{Vu,        { Description -> "Left-Up-Mixing-Matrix"}},
{Vd,        { Description -> "Left-Down-Mixing-Matrix"}},
{Uu,        { Description -> "Right-Up-Mixing-Matrix"}},
{Ud,        { Description -> "Right-Down-Mixing-Matrix"}},
{Ve,        { Description -> "Left-Lepton-Mixing-Matrix"}},
{Ue,        { Description -> "Right-Lepton-Mixing-Matrix"}},

{mchi,  { LaTeX -> "m_\chi",
               OutputName -> mchi,
               Real -> True,
               LesHouches -> {BSMPARAMS, 1} }},

{ychi,  { LaTeX -> "y_\chi",
               OutputName -> ychi,
               Real -> True,
               LesHouches -> {BSMPARAMS, 2} }},

{ma_sq,  { LaTeX -> "m_a^2",
               OutputName -> ma_sq,
               Real -> True,
               LesHouches -> {BSMPARAMS, 3} }},

{kap_aHH,  { LaTeX -> "\kappa_{aHH}",
               OutputName -> kap_aHH,
               Real -> True,
               LesHouches -> {BSMPARAMS, 4} }},

{mu11_sq,  { LaTeX -> "\mu_{11}^2",
               OutputName -> mu11_sq,
               Real -> True,
               LesHouches -> {BSMPARAMS, 5} }},

{mu22_sq,  { LaTeX -> "\mu_{22}^2",
               OutputName -> mu22_sq,
               Real -> True,
               LesHouches -> {BSMPARAMS, 6} }},

{lam1,  { LaTeX -> "\lambda_1",
               OutputName -> lam1,
               Real -> True,
               LesHouches -> {BSMPARAMS, 7} }},

{lam2,  { LaTeX -> "\lambda_2",
               OutputName -> lam2,
               Real -> True,
               LesHouches -> {BSMPARAMS, 8} }},

{lam3,  { LaTeX -> "\lambda_3",
               OutputName -> lam3,
               Real -> True,
               LesHouches -> {BSMPARAMS, 9} }},

{Yu2,  { LaTeX -> "Y_u^{(2)}",
               OutputName -> Yu2,
               Real -> False,
               LesHouches -> YUKAWAU }},

{Yd1,  { LaTeX -> "Y_d^{(1)}",
               OutputName -> Yd1,
               Real -> False,
               LesHouches -> YUKAWAD }},

{Ye1,  { LaTeX -> "Y_e^{(1)}",
               OutputName -> Ye1,
               Real -> False,
               LesHouches -> YUKAWAE }},

{ZH,  { Description -> "Scalar-Mixing-Matrix-hh",
               OutputName -> ZH,
               Real -> False,
               LesHouches -> ZHMIX }},

{ZA,  { Description -> "Scalar-Mixing-Matrix-Ah",
               OutputName -> ZA,
               Real -> False,
               LesHouches -> ZAMIX }},

{ZP,  { Description -> "Scalar-Mixing-Matrix-Hm",
               OutputName -> ZP,
               Real -> False,
               LesHouches -> ZPMIX }},

{PhasechiR,  { LaTeX -> "PhasechiR",
               OutputName -> PhasechiR,
               Real -> False,
               LesHouches -> {PHASES, 1} }}

 };
