(*
 * particles.m  —  SARAH particle content
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)

ParticleDefinitions[GaugeES] = {

{VB,   { Description -> "B-Boson"}},
{VG,   { Description -> "Gluon"}},
{VWB,  { Description -> "W-Bosons"}},
{gB,   { Description -> "B-Boson Ghost"}},
{gG,   { Description -> "Gluon Ghost" }},
{gWB,  { Description -> "W-Boson Ghost"}},

{H1, {
     PDG -> {9931297, 9937732},
     Width -> Automatic,
     Mass -> LesHouches,
     LaTeX -> "H1",
     OutputName -> "H1" }},

{H2, {
     PDG -> {9927679, 9912124},
     Width -> Automatic,
     Mass -> LesHouches,
     LaTeX -> "H2",
     OutputName -> "H2" }},

{a0, {
     PDG -> {9975327},
     Width -> Automatic,
     Mass -> LesHouches,
     LaTeX -> "a0",
     OutputName -> "a0" }},

{Fd1, {PDG -> {0}, Width -> 0, Mass -> Automatic, LaTeX -> "d_1", OutputName -> "Fd1"}},
{Fd2, {PDG -> {0}, Width -> 0, Mass -> Automatic, LaTeX -> "d_2", OutputName -> "Fd2"}},
{Fu1, {PDG -> {0}, Width -> 0, Mass -> Automatic, LaTeX -> "u_1", OutputName -> "Fu1"}},
{Fu2, {PDG -> {0}, Width -> 0, Mass -> Automatic, LaTeX -> "u_2", OutputName -> "Fu2"}},
{Fe1, {PDG -> {0}, Width -> 0, Mass -> Automatic, LaTeX -> "e_1", OutputName -> "Fe1"}},
{Fe2, {PDG -> {0}, Width -> 0, Mass -> Automatic, LaTeX -> "e_2", OutputName -> "Fe2"}},
{Fv1, {PDG -> {0}, Width -> 0, Mass -> Automatic, LaTeX -> "v_1", OutputName -> "Fv1"}},

{Fchi1, {PDG -> {0}, Width -> 0, Mass -> Automatic, LaTeX -> "Fchi1", OutputName -> "Fchi1"}},

{Fchi2, {PDG -> {0}, Width -> 0, Mass -> Automatic, LaTeX -> "Fchi2", OutputName -> "Fchi2"}}

};


ParticleDefinitions[EWSB] = {

{VP,   { Description -> "Photon" }},
{VZ,   { Description -> "Z-Boson" }},
{VG,   { Description -> "Gluon" }},
{VWp,  { Description -> "W+ - Boson" }},
{gP,   { Description -> "Photon Ghost" }},
{gWp,  { Description -> "Positive W+ - Boson Ghost" }},
{gWpC, { Description -> "Negative W+ - Boson Ghost" }},
{gZ,   { Description -> "Z-Boson Ghost" }},
{gG,   { Description -> "Gluon Ghost" }},

{Fd,   { Description -> "Down-Quarks" }},
{Fu,   { Description -> "Up-Quarks" }},
{Fe,   { Description -> "Leptons" }},
{Fv,   { Description -> "Neutrinos" }},

{hh, {
     Description -> "BSM scalar mass eigenstate hh",
     PDG -> {9915085, 9956724},
     Width -> Automatic,
     Mass -> LesHouches,
     LaTeX -> "hh",
     OutputName -> "hh" }},

{Ah, {
     Description -> "BSM scalar mass eigenstate Ah",
     PDG -> {9931722, 9949515, 9931569},
     Width -> Automatic,
     Mass -> LesHouches,
     LaTeX -> "Ah",
     OutputName -> "Ah" }},

{Hm, {
     Description -> "BSM scalar mass eigenstate Hm",
     PDG -> {9942955, 9920911},
     Width -> Automatic,
     Mass -> LesHouches,
     LaTeX -> "Hm",
     OutputName -> "Hm" }},

{Fchi, {
     Description -> "BSM fermion mass eigenstate chi",
     PDG -> {9989932},
     Width -> Automatic,
     Mass -> LesHouches,
     ElectricCharge -> 0,
     LaTeX -> "chi",
     OutputName -> "chi" }}

};


WeylFermionAndIndermediate = {

{H,      { PDG -> {0},
            Width -> 0,
            Mass -> Automatic,
            LaTeX -> "H",
            OutputName -> "" }},

{dR,     { LaTeX -> "d_R" }},
{eR,     { LaTeX -> "e_R" }},
{LL,     { LaTeX -> "l" }},
{uR,     { LaTeX -> "u_R" }},
{q,      { LaTeX -> "q" }},
{eL,     { LaTeX -> "e_L" }},
{dL,     { LaTeX -> "d_L" }},
{uL,     { LaTeX -> "u_L" }},
{vL,     { LaTeX -> "\\nu_L" }},

{DR,     { LaTeX -> "D_R" }},
{ER,     { LaTeX -> "E_R" }},
{UR,     { LaTeX -> "U_R" }},
{EL,     { LaTeX -> "E_L" }},
{DL,     { LaTeX -> "D_L" }},
{UL,     { LaTeX -> "U_L" }},

{chiL,  { LaTeX -> "chiL" }},
{chiR,  { LaTeX -> "chiR" }},
{ChiL,  { LaTeX -> "ChiL" }},
{ChiR,  { LaTeX -> "ChiR" }},
{chi,  { LaTeX -> "chi" }},
{H1,  { LaTeX -> "H1" }},
{H1p,  { LaTeX -> "H1p" }},
{H10,  { LaTeX -> "H10" }},
{H2,  { LaTeX -> "H2" }},
{H2p,  { LaTeX -> "H2p" }},
{H20,  { LaTeX -> "H20" }},
{a0,  { LaTeX -> "a0" }}

};
