(*
 * SPheno.m  —  SARAH SPheno interface configuration
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)

OnlyLowEnergySPheno = True;

MINPAR={
        {1,mchi},
        {2,ychi},
        {3,ma_sq},
        {4,kap_aHH},
        {5,mu11_sq},
        {6,mu22_sq},
        {7,lam1},
        {8,lam2},
        {9,lam3},
        {10,Yu2},
        {11,Yd1},
        {12,Ye1}
        };

RealParameters = {TanBeta};

ParametersToSolveTadpoles = {Mvd2, Mvu2};

DEFINITION[MatchingConditions]= {
 {vd, vSM*Cos[ArcTan[TanBeta]]},
 {vu, vSM*Sin[ArcTan[TanBeta]]},
 {Ye, YeSM*vSM/vd},
 {Yd, YdSM*vSM/vd},
 {Yu, YuSM*vSM/vu},
 {g1, g1SM},
 {g2, g2SM},
 {g3, g3SM}
 };

BoundaryLowScaleInput={
  {mchi,mchiInput},
  {ychi,ychiInput},
  {ma_sq,ma_sqInput},
  {kap_aHH,kap_aHHInput},
  {mu11_sq,mu11_sqInput},
  {mu22_sq,mu22_sqInput},
  {lam1,lam1Input},
  {lam2,lam2Input},
  {lam3,lam3Input},
  {Yu2,Yu2Input},
  {Yd1,Yd1Input},
  {Ye1,Ye1Input},
  {TanBeta, TanBeta}
};

ListDecayParticles = {Fu, Fe, Fd, hh, Ah, Hm};

ListDecayParticles3B = {{Fu,"Fu.f90"},{Fe,"Fe.f90"},{Fd,"Fd.f90"}};

DefaultInputValues ={
    mchiInput -> 100.0,
    ychiInput -> 1.0,
    ma_sqInput -> 10000.0,
    kap_aHHInput -> 100.0,
    mu11_sqInput -> -7500.0,
    mu22_sqInput -> -7500.0,
    lam1Input -> 0.5,
    lam2Input -> 0.5,
    lam3Input -> 0.1,
    Yu2Input -> 1.0,
    Yd1Input -> 0.1,
    Ye1Input -> 0.01,
    TanBeta -> 10
    };

RenConditionsDecays={
{dCosTW, 1/2*Cos[ThetaW] * (PiVWp/(MVWp^2) - PiVZ/(mVZ^2)) },
{dSinTW, -dCosTW/Tan[ThetaW]},
{dg2, 1/2*g2*(derPiVPheavy0 + PiVPlightMZ/MVZ^2 - (-(PiVWp/MVWp^2) + PiVZ/MVZ^2)/Tan[ThetaW]^2 + (2*PiVZVP*Tan[ThetaW])/MVZ^2)  },
{dg1, dg2*Tan[ThetaW]+g2*dSinTW/Cos[ThetaW]- dCosTW*g2*Tan[ThetaW]/Cos[ThetaW]}
};

