(*
 * <Name>.m  —  SARAH model file
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)

Off[General::spell]

Model`Name = "SingletDoublet";
Model`NameLaTeX = "SingletDoublet";
Model`Authors = "John Tamanas";
Model`Date = "2026-04-22";

Global[[1]] = {Z[2], DMParity};

NameOfStates = {GaugeES, EWSB};

DEFINITION[GaugeES][LagrangianInput] = {
    {LagHC,   {AddHC -> True}},
    {LagNoHC, {AddHC -> False}}
};

Gauge[[1]] = {B, U[1], hypercharge, g1, False, 1};
Gauge[[2]] = {WB, SU[2], left, g2, True, 1};
Gauge[[3]] = {G, SU[3], color, g3, False, 1};

FermionFields[[1]] = {q, 3, {uL, dL},  1/6, 2,  3, 1};
FermionFields[[2]] = {LL, 3, {vL, eL}, -1/2, 2,  1, 1};
FermionFields[[3]] = {d, 3, conj[dR],    1/3, 1, -3, 1};
FermionFields[[4]] = {u, 3, conj[uR],   -2/3, 1, -3, 1};
FermionFields[[5]] = {e, 3, conj[eR],      1, 1,  1, 1};

FermionFields[[6]] = {FS, 1, s0, 0, 1, 1, -1};
FermionFields[[7]] = {PsiDd, 1, {PsiDd0, PsiDdm}, -1/2, 2, 1, -1};
FermionFields[[8]] = {PsiDu, 1, {PsiDup, PsiDu0}, 1/2, 2, 1, -1};

ScalarFields[[1]] = {H, 1, {Hp, H0},  1/2, 2,  1, 1};

LagNoHC = -mu2 conj[H].H -1/2 \[Lambda] conj[H].H.conj[H].H;

LagHC = -(Yd conj[H].d.q + Ye conj[H].e.LL -Yu H.u.q + 1/2 MS FS.FS + MPsi PsiDu.PsiDd + yh1 conj[H].FS.PsiDu + yh2 H.FS.PsiDd);

DEFINITION[EWSB][MatterSector] = {
  {{{dL}, {conj[dR]}}, {{DL, Vd}, {DR, Ud}}},
  {{{uL}, {conj[uR]}}, {{UL, Vu}, {UR, Uu}}},
  {{{eL}, {conj[eR]}}, {{EL, Ve}, {ER, Ue}}},
  {{s0, PsiDd0, PsiDu0}, {Chi, ZN}},
  {{{PsiDdm}, {PsiDup}}, {{ChiM, UM}, {ChiP, UP}}}
};

DEFINITION[GaugeES][DiracSpinors] = {
  Fd1 -> {dL, 0},
  Fd2 -> {0, dR},
  Fu1 -> {uL, 0},
  Fu2 -> {0, uR},
  Fe1 -> {eL, 0},
  Fe2 -> {0, eR},
  Fv1 -> {vL, 0},
  FFS0 -> {s0, 0},
  FPsiDd0 -> {PsiDd0, 0},
  FPsiDd1 -> {PsiDdm, 0},
  FPsiDu0 -> {PsiDup, 0},
  FPsiDu1 -> {PsiDu0, 0}
};

DEFINITION[EWSB][GaugeSector] = {
  {{VB, VWB[3]}, {VP, VZ}, ZZ},
  {{VWB[1], VWB[2]}, {VWp, conj[VWp]}, ZW}
};

DEFINITION[EWSB][VEVs] = {
  {H0, {v, 1/Sqrt[2]}, {Ah, \[ImaginaryI]/Sqrt[2]}, {hh, 1/Sqrt[2]}}
};

DEFINITION[EWSB][Phases] = {
  {s0, PhaseFS}
};

DEFINITION[EWSB][DiracSpinors] = {
  Fd  -> {DL,  conj[DR]},
  Fe  -> {EL,  conj[ER]},
  Fu  -> {UL,  conj[UR]},
  Fv  -> {vL,  0},
  FChi -> {Chi, conj[Chi]},
  FChiM -> {ChiM, conj[ChiP]}
};
