(*
 * SPheno.m  —  SARAH SPheno interface configuration
 * Generated by hephaestus /sarah-build from ModelSpec.
 * DO NOT EDIT by hand; re-run /sarah-build to regenerate.
 *)

OnlyLowEnergySPheno = True;

MINPAR={
        {1,MS},
        {2,MPsi},
        {3,yh1},
        {4,yh2}
        };

ParametersToSolveTadpoles = {mu2};

DEFINITION[MatchingConditions]= {
 {v, vSM},
 {Ye, YeSM},
 {Yd, YdSM},
 {Yu, YuSM},
 {g1, g1SM},
 {g2, g2SM},
 {g3, g3SM}};

BoundaryLowScaleInput={
  {MS,MSInput},
  {MPsi,MPsiInput},
  {yh1,yh1Input},
  {yh2,yh2Input}
};

ListDecayParticles = {Fu, Fe, Fd, hh, Chi, ChiM};

ListDecayParticles3B = {{Fu,"Fu.f90"},{Fe,"Fe.f90"},{Fd,"Fd.f90"}};

DefaultInputValues ={
    MSInput -> 300.0,
    MPsiInput -> 500.0,
    yh1Input -> 0.3,
    yh2Input -> 0.3
    };

RenConditionsDecays={
{dCosTW, 1/2*Cos[ThetaW] * (PiVWp/(MVWp^2) - PiVZ/(mVZ^2)) },
{dSinTW, -dCosTW/Tan[ThetaW]},
{dg2, 1/2*g2*(derPiVPheavy0 + PiVPlightMZ/MVZ^2 - (-(PiVWp/MVWp^2) + PiVZ/MVZ^2)/Tan[ThetaW]^2 + (2*PiVZVP*Tan[ThetaW])/MVZ^2)  },
{dg1, dg2*Tan[ThetaW]+g2*dSinTW/Cos[ThetaW]- dCosTW*g2*Tan[ThetaW]/Cos[ThetaW]}
};

