"""
validate_goldens.py — Golden-file oracle: stage + wolframscript drive + error grep.

This is the correctness gate for T15a/b/c goldens (plan-final.md §T19,
design-final.md §10.3). For each golden `.m` file tree, it:

1. Stages the tree into `$sarah_path/Private-Models/<SarahName>/` via
   :func:`stage.stage` (wipes stale .m and .mx caches — design §6.2).
2. Invokes ``wolframscript`` with the SARAH load + ``Start["<Name>"]`` +
   ``CheckModel[]`` + optional ``MakeUFO[]`` / ``MakeSPheno[]`` incantation.
3. Parses stdout + stderr for the forbidden error patterns.
4. Returns exit 0 on success, non-zero on failure with descriptive JSON.
5. Cleans up the staged tree on exit.

Forbidden error patterns (design §10.3):
    - ``ModelFile::MissingModel``  — Start[] couldn't find the model.
    - ``ModelFile::Aborted``       — Start[] aborted mid-load.
    - ``CheckModel::*Abort*``      — CheckModel[] aborted.
    - ``MatterSector::parseError`` — matter-sector block failed to parse.
    - Non-zero wolframscript exit status is also a failure.

For ``MakeUFO[]`` success: after the run, confirm
``$sarah_path/Output/<SarahName>/`` contains a ``UFO/`` subtree with
``particles.py`` (SARAH's standard UFO filename).

For ``MakeSPheno[]`` success: after the run, confirm
``$sarah_path/Output/<SarahName>/EWSB/SPheno/`` exists and contains
``SPheno.m.f90`` (SARAH's main SPheno generator output).

CLI:
    python3 scripts/validate_goldens.py \
        --model <name> \
        --goldens-dir <path-to-goldens/name/> \
        [--outputs ufo,spheno] \
        [--sarah-path <path>] \
        [--wolframscript <path>] \
        [--keep-staged]

Exit codes:
    0 — PASS (prints {"status": "valid"} JSON to stdout).
    1 — FAIL (prints {"status": "invalid", "code": ..., "context": {...}} JSON).
    2 — Usage / environment error (missing wolframscript, missing SARAH,
        missing goldens file).

The CLI is intentionally opt-in (not pytest): SARAH isn't in CI, and this
script is the equivalent of a pre-commit hook that developers run locally
before committing goldens regenerated by T15a/b/c.

Library API:
    from validate_goldens import validate, ValidationResult
    result = validate(
        model="singlet_doublet",
        goldens_dir=Path("tests/goldens/singlet_doublet"),
        outputs=["ufo", "spheno"],
        sarah_path=Path("/Users/yianni/SARAH/SARAH-4.15.3"),
        wolframscript=Path("/usr/local/bin/wolframscript"),
    )
    if result.ok:
        ...
"""

from __future__ import annotations

import sys
assert sys.version_info >= (3, 10), "hephaestus requires Python >= 3.10"

import argparse
import dataclasses
import json
import os
import re
import shutil
import subprocess
from pathlib import Path


# ---------------------------------------------------------------------------
# sys.path setup (we import sibling modules without installation)
# ---------------------------------------------------------------------------

_SCRIPT_DIR = Path(__file__).resolve().parent
_SKILL_DIR = _SCRIPT_DIR.parent
_SHARED_DIR = _SKILL_DIR.parent / "_shared"

for _p in [str(_SCRIPT_DIR), str(_SHARED_DIR)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from sarah_name import modelspec_name_to_sarah  # noqa: E402
from stage import stage as stage_rendered       # noqa: E402


# ---------------------------------------------------------------------------
# Error-pattern grammar (design §10.3)
# ---------------------------------------------------------------------------

#: Fatal SARAH error signatures.  If any line of stdout+stderr matches one
#: of these regexes, the model is considered invalid.  The order here is
#: the order in which we report (first match wins in the final code
#: assignment).
#:
#: Cycle-2 hardening (T15a cycle-1 review oracle-gap fix): added the five
#: CheckModelFiles::*/Model::*/Set::partw patterns that T15a cycle-1 proved
#: SARAH emits when parameters.m / particles.m are incomplete (missing
#: mixing-matrix declarations, under-sized PDG lists, phases without decls).
#: Without these, SARAH silently produces UFO Particle() entries named
#: 'None' with Param.$Failed masses and zero DM vertices — invalid, but the
#: oracle returned VALID.  See cycle-1-review.md for the full diagnosis.
_FORBIDDEN_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("MODEL_FILE_MISSING",   re.compile(r"ModelFile::MissingModel")),
    ("MODEL_FILE_ABORTED",   re.compile(r"ModelFile::Aborted")),
    ("CHECKMODEL_ABORTED",   re.compile(r"CheckModel::.*Abort", re.IGNORECASE)),
    ("MATTERSECTOR_PARSE",   re.compile(r"MatterSector::parseError")),
    ("MISSING_PARAMETER",    re.compile(r"CheckModelFiles::MissingParameter")),
    ("MISSING_PARTICLE",     re.compile(r"CheckModelFiles::MissingParticle")),
    ("MISSING_OUTPUTNAME",   re.compile(r"CheckModelFiles::MissingOutputName(?:Parameter)?")),
    ("MODEL_NO_EC",          re.compile(r"Model::NoEC")),
    ("SET_PARTW",            re.compile(r"Set::partw")),
)


# ---------------------------------------------------------------------------
# Public types
# ---------------------------------------------------------------------------

@dataclasses.dataclass(frozen=True)
class ValidationResult:
    """Outcome of :func:`validate`.

    Attributes:
        ok:       True iff the model passed all checks.
        code:     One of ``"VALID"``, ``"MODEL_FILE_MISSING"``,
                  ``"MODEL_FILE_ABORTED"``, ``"CHECKMODEL_ABORTED"``,
                  ``"MATTERSECTOR_PARSE"``, ``"MISSING_PARAMETER"``,
                  ``"MISSING_PARTICLE"``, ``"MISSING_OUTPUTNAME"``,
                  ``"MODEL_NO_EC"``, ``"SET_PARTW"``,
                  ``"WOLFRAMSCRIPT_NONZERO"``,
                  ``"UFO_MISSING"``, ``"SPHENO_MISSING"``.
        message:  Short human-readable summary.
        context:  Machine-readable context (matched line, log path, etc).
    """
    ok: bool
    code: str
    message: str
    context: dict

    def as_json(self) -> dict:
        """Return the canonical CLI JSON payload."""
        if self.ok:
            return {"status": "valid", "code": self.code, "context": self.context}
        return {"status": "invalid", "code": self.code, "message": self.message, "context": self.context}


# ---------------------------------------------------------------------------
# Wolframscript driver
# ---------------------------------------------------------------------------

#: Map from spec.outputs entries to their Mathematica calls.  Mirrors the
#: dispatch table in ``run_sarah.py`` but local to this module to avoid
#: importing run_sarah's config machinery.
_MAKE_DISPATCH: dict[str, str] = {
    "ufo":    "MakeUFO[]",
    "spheno": "MakeSPheno[]",
}


def _build_code(sarah_path: Path, sarah_name: str, outputs: list[str]) -> str:
    """Build the wolframscript ``-code`` payload.

    The ``AppendTo[$Path, "<sarah_path>"]`` + ``Needs["SARAH`"]`` idiom
    mirrors the T05a spike (tests/spikes/run_spike.sh).  We always run
    ``Start[]`` + ``CheckModel[]``; make commands are appended in the
    order listed in *outputs*.
    """
    make_cmds = "; ".join(_MAKE_DISPATCH[o] for o in outputs)
    if make_cmds:
        make_cmds += ";"
    return (
        f'AppendTo[$Path, "{sarah_path}"]; '
        f'Needs["SARAH`"]; '
        f'Start["{sarah_name}"]; '
        f'CheckModel[]; '
        + make_cmds
        + ' Print["[validate_goldens] OK"];'
    )


def _scan_for_forbidden(log_text: str) -> tuple[str, str] | None:
    """Return (code, matched_line) if *log_text* contains a forbidden pattern.

    Returns the first match found.  None if clean.
    """
    for line in log_text.splitlines():
        for code, pattern in _FORBIDDEN_PATTERNS:
            if pattern.search(line):
                return code, line.strip()
    return None


def _read_goldens(goldens_dir: Path, sarah_name: str) -> dict[str, str]:
    """Load the golden `.m` files into a dict suitable for :func:`stage.stage`.

    Expects at minimum ``<sarah_name>.m``.  Additional ``*.m`` files in
    the directory are included (parameters.m, particles.m, SPheno.m).
    The ``.sarah_build_key`` sentinel (if present) is ignored — stage()
    will stamp a fresh one.
    """
    if not goldens_dir.is_dir():
        raise FileNotFoundError(f"goldens dir not found: {goldens_dir}")
    main = goldens_dir / f"{sarah_name}.m"
    if not main.is_file():
        raise FileNotFoundError(
            f"expected main model file {main} not found "
            f"(goldens_dir must contain <SarahName>.m)"
        )
    rendered: dict[str, str] = {}
    for path in sorted(goldens_dir.iterdir()):
        if path.name == ".sarah_build_key":
            continue
        if path.is_file() and path.suffix == ".m":
            rendered[path.name] = path.read_text(encoding="utf-8")
    return rendered


# ---------------------------------------------------------------------------
# Post-run output-tree checks
# ---------------------------------------------------------------------------

def _check_ufo_tree(sarah_path: Path, sarah_name: str) -> tuple[bool, Path]:
    """Confirm SARAH emitted a UFO tree.

    SARAH writes to ``$sarah_path/Output/<SarahName>/EWSB/UFO/``
    (see `design-final.md` §6.6).  We accept the run as UFO-valid if
    any directory under that root contains ``particles.py`` (SARAH's
    canonical UFO filename; also a good sanity check that the .py files
    were generated, not just the dir).
    """
    output_root = sarah_path / "Output" / sarah_name
    if not output_root.is_dir():
        return False, output_root
    for ufo_dir in output_root.rglob("UFO"):
        if ufo_dir.is_dir() and (ufo_dir / "particles.py").is_file():
            return True, ufo_dir
    return False, output_root


def _check_spheno_tree(sarah_path: Path, sarah_name: str) -> tuple[bool, Path]:
    """Confirm SARAH emitted a SPheno Fortran source tree.

    SARAH writes to ``$sarah_path/Output/<SarahName>/EWSB/SPheno/``.
    We accept the run as SPheno-valid if any directory under the Output
    root named ``SPheno`` contains a ``SPheno.m.f90`` file (SARAH's main
    SPheno generator output).
    """
    output_root = sarah_path / "Output" / sarah_name
    if not output_root.is_dir():
        return False, output_root
    for spheno_dir in output_root.rglob("SPheno"):
        if spheno_dir.is_dir():
            # Any .f90 file is evidence of a real SPheno build; "SPheno.m.f90"
            # is preferred but we also accept any *.f90.
            if (spheno_dir / "SPheno.m.f90").is_file():
                return True, spheno_dir
            if any(p.suffix == ".f90" for p in spheno_dir.iterdir()):
                return True, spheno_dir
    return False, output_root


# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------

def _cleanup_staged(sarah_path: Path, sarah_name: str) -> None:
    """Remove ``$sarah_path/Private-Models/<SarahName>/`` if it exists.

    Silently tolerates rm failures — this is best-effort cleanup and we
    don't want to mask the real validation error with a cleanup error.
    """
    staged = sarah_path / "Private-Models" / sarah_name
    if staged.exists():
        try:
            shutil.rmtree(staged)
        except OSError:
            # Don't shadow the real error.
            pass


# ---------------------------------------------------------------------------
# Core driver (test-seam friendly)
# ---------------------------------------------------------------------------

def _run_wolframscript(
    wolframscript: Path,
    sarah_path: Path,
    sarah_name: str,
    outputs: list[str],
    timeout: float | None = None,
) -> subprocess.CompletedProcess:
    """Invoke wolframscript with the SARAH driver code.

    Extracted as its own function so tests can monkeypatch it.  We
    capture both stdout and stderr as text; SARAH messages go to stderr
    but wolframscript sometimes reroutes depending on phase.
    """
    code = _build_code(sarah_path, sarah_name, outputs)
    cmd = [str(wolframscript), "-code", code]
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def validate(
    model: str,
    goldens_dir: Path,
    outputs: list[str] | None = None,
    sarah_path: Path | None = None,
    wolframscript: Path | None = None,
    keep_staged: bool = False,
    timeout: float | None = None,
) -> ValidationResult:
    """Run the full validate pipeline.

    Args:
        model:         Spec-level model name (snake_case).  Gets converted
                       to the SARAH name via ``modelspec_name_to_sarah``.
        goldens_dir:   Directory containing ``<SarahName>.m`` + friends.
        outputs:       List of output targets to build, any of ``["ufo",
                       "spheno"]``.  Defaults to ``[]`` (Start + CheckModel
                       only).  Per design §11.3 dark_su3 render-only bar,
                       callers may pass ``[]`` to skip MakeUFO.
        sarah_path:    Root of the SARAH install (contains SARAH.m).
                       Defaults to ``/Users/yianni/SARAH/SARAH-4.15.3``.
        wolframscript: Path to the wolframscript binary.  Defaults to
                       ``/usr/local/bin/wolframscript``.
        keep_staged:   If True, do NOT rmtree the staged Private-Models
                       dir on exit (useful for debugging).
        timeout:       Passed to subprocess.run.

    Returns:
        A :class:`ValidationResult`.  Caller decides whether to exit 0/1.

    Raises:
        FileNotFoundError: Environment or goldens missing.  Callers who
            want this to become exit-2 should catch and translate.
    """
    if outputs is None:
        outputs = []
    # Validate outputs list eagerly so we can produce a useful error
    # before touching the filesystem.
    for o in outputs:
        if o not in _MAKE_DISPATCH:
            raise ValueError(
                f"unknown output target {o!r}; must be one of {sorted(_MAKE_DISPATCH)}"
            )

    sarah_path = Path(sarah_path) if sarah_path else Path("/Users/yianni/SARAH/SARAH-4.15.3")
    wolframscript = Path(wolframscript) if wolframscript else Path("/usr/local/bin/wolframscript")

    if not sarah_path.is_dir():
        raise FileNotFoundError(f"sarah_path is not a directory: {sarah_path}")
    if not wolframscript.exists():
        raise FileNotFoundError(f"wolframscript not found: {wolframscript}")

    sarah_name = modelspec_name_to_sarah(model)

    # 1. Load goldens from disk
    rendered = _read_goldens(goldens_dir, sarah_name)

    # 2. Stage into Private-Models/
    cache_key = f"validate_goldens:{model}"
    staged_dir = stage_rendered(rendered, sarah_path, sarah_name, cache_key)

    try:
        # 3. Invoke wolframscript
        try:
            proc = _run_wolframscript(
                wolframscript=wolframscript,
                sarah_path=sarah_path,
                sarah_name=sarah_name,
                outputs=outputs,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired as exc:
            return ValidationResult(
                ok=False,
                code="WOLFRAMSCRIPT_TIMEOUT",
                message=f"wolframscript timed out after {exc.timeout}s",
                context={"timeout": exc.timeout, "cmd": exc.cmd},
            )

        combined = (proc.stdout or "") + "\n" + (proc.stderr or "")

        # 4. Pattern scan (run even if returncode == 0 — SARAH sometimes
        # emits fatal Messages without failing the process)
        hit = _scan_for_forbidden(combined)
        if hit is not None:
            code, matched = hit
            return ValidationResult(
                ok=False,
                code=code,
                message=f"SARAH emitted forbidden pattern: {matched}",
                context={
                    "matched_line": matched,
                    "returncode": proc.returncode,
                    "staged_dir": str(staged_dir),
                },
            )

        # 5. Non-zero exit without a forbidden pattern: still a failure
        if proc.returncode != 0:
            tail = combined[-2000:]
            return ValidationResult(
                ok=False,
                code="WOLFRAMSCRIPT_NONZERO",
                message=f"wolframscript exited {proc.returncode}",
                context={
                    "returncode": proc.returncode,
                    "log_tail": tail,
                    "staged_dir": str(staged_dir),
                },
            )

        # 6. Output-tree checks for each requested output
        for o in outputs:
            if o == "ufo":
                ok, where = _check_ufo_tree(sarah_path, sarah_name)
                if not ok:
                    return ValidationResult(
                        ok=False,
                        code="UFO_MISSING",
                        message=f"MakeUFO[] did not produce a UFO tree under {where}",
                        context={
                            "expected_root": str(where),
                            "staged_dir": str(staged_dir),
                        },
                    )
            elif o == "spheno":
                ok, where = _check_spheno_tree(sarah_path, sarah_name)
                if not ok:
                    return ValidationResult(
                        ok=False,
                        code="SPHENO_MISSING",
                        message=f"MakeSPheno[] did not produce a SPheno tree under {where}",
                        context={
                            "expected_root": str(where),
                            "staged_dir": str(staged_dir),
                        },
                    )

        # 7. All checks passed.
        return ValidationResult(
            ok=True,
            code="VALID",
            message="all checks passed",
            context={
                "sarah_name": sarah_name,
                "outputs_checked": list(outputs),
                "staged_dir": str(staged_dir),
            },
        )
    finally:
        if not keep_staged:
            _cleanup_staged(sarah_path, sarah_name)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_outputs(raw: str | None) -> list[str]:
    if not raw:
        return []
    return [o.strip() for o in raw.split(",") if o.strip()]


def _make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Validate a SARAH golden-file tree: stage into Private-Models/, "
            "invoke wolframscript, grep for forbidden SARAH errors."
        ),
        prog="validate_goldens.py",
    )
    parser.add_argument(
        "--model",
        required=True,
        help="Spec-level model name (snake_case, e.g. 'singlet_doublet').",
    )
    parser.add_argument(
        "--goldens-dir",
        required=True,
        type=Path,
        help="Path to the goldens directory (e.g. tests/goldens/singlet_doublet/).",
    )
    parser.add_argument(
        "--outputs",
        default="",
        help=(
            "Comma-separated list of outputs to build and verify: "
            "'ufo', 'spheno', or 'ufo,spheno'.  Empty (default) runs "
            "Start + CheckModel only."
        ),
    )
    parser.add_argument(
        "--sarah-path",
        default=os.environ.get("SARAH_PATH", "/Users/yianni/SARAH/SARAH-4.15.3"),
        type=Path,
        help="Root of SARAH install (env: SARAH_PATH).",
    )
    parser.add_argument(
        "--wolframscript",
        default=os.environ.get("WOLFRAMSCRIPT", "/usr/local/bin/wolframscript"),
        type=Path,
        help="Path to wolframscript binary (env: WOLFRAMSCRIPT).",
    )
    parser.add_argument(
        "--keep-staged",
        action="store_true",
        help="Do NOT remove Private-Models/<Name>/ on exit (debug aid).",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=None,
        help="Seconds before wolframscript is killed (default: no timeout).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _make_parser().parse_args(argv)
    outputs = _parse_outputs(args.outputs)

    try:
        result = validate(
            model=args.model,
            goldens_dir=args.goldens_dir,
            outputs=outputs,
            sarah_path=args.sarah_path,
            wolframscript=args.wolframscript,
            keep_staged=args.keep_staged,
            timeout=args.timeout,
        )
    except FileNotFoundError as exc:
        print(json.dumps({
            "status": "invalid",
            "code": "ENVIRONMENT_MISSING",
            "message": str(exc),
            "context": {},
        }))
        return 2
    except ValueError as exc:
        print(json.dumps({
            "status": "invalid",
            "code": "BAD_ARGUMENT",
            "message": str(exc),
            "context": {},
        }))
        return 2

    payload = result.as_json()
    print(json.dumps(payload))
    return 0 if result.ok else 1


if __name__ == "__main__":
    sys.exit(main())
