C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(2,3)
C     
      SUBROUTINE SVV1_0(S1, V2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 S1(*)
      COMPLEX*16 TMP0
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 VERTEX
      TMP0 = (V3(3)*V2(3)-V3(4)*V2(4)-V3(5)*V2(5)-V3(6)*V2(6))
      VERTEX = COUP*(-CI * TMP0*S1(3))
      END


