C     -----------------------------------------------------------------
C     -------c
      SUBROUTINE GETFSMASSES_ANN(PMASS, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine which is dynamically generated by the MadDM
C      python     c
C     codes reads through the pmass.inc files to get the external
C      particle   c
C     masses for the annihilation processes.                          
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'

C     input parameters
      INTEGER I, J, K

C     
      IF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.1)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MZ)
        PMASS(4)=ABS(MDL_MZ)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.2)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MZ)
        PMASS(4)=ABS(MDL_MH)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.3)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MH)
        PMASS(4)=ABS(MDL_MH)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.4)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MWP)
        PMASS(4)=ABS(MDL_MWP)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.5)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MD1)
        PMASS(4)=ABS(MDL_MD1)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.6)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MU1)
        PMASS(4)=ABS(MDL_MU1)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.7)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MD2)
        PMASS(4)=ABS(MDL_MD2)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.8)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MU2)
        PMASS(4)=ABS(MDL_MU2)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.9)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MD3)
        PMASS(4)=ABS(MDL_MD3)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.10)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MU3)
        PMASS(4)=ABS(MDL_MU3)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.11)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_ME1)
        PMASS(4)=ABS(MDL_ME1)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.12)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_ME2)
        PMASS(4)=ABS(MDL_ME2)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.13)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_ME3)
        PMASS(4)=ABS(MDL_ME3)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.14)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ZERO
        PMASS(4)=ZERO
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.15)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ZERO
        PMASS(4)=ZERO
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.16)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ZERO
        PMASS(4)=ZERO
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.17)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MD1)
        PMASS(4)=ABS(MDL_MD2)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.18)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MD1)
        PMASS(4)=ABS(MDL_MD3)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.19)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MU1)
        PMASS(4)=ABS(MDL_MU2)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.20)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MU1)
        PMASS(4)=ABS(MDL_MU3)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.21)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MD2)
        PMASS(4)=ABS(MDL_MD1)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.22)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MD2)
        PMASS(4)=ABS(MDL_MD3)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.23)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MU2)
        PMASS(4)=ABS(MDL_MU1)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.24)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MU2)
        PMASS(4)=ABS(MDL_MU3)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.25)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MD3)
        PMASS(4)=ABS(MDL_MD1)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.26)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MD3)
        PMASS(4)=ABS(MDL_MD2)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.27)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MU3)
        PMASS(4)=ABS(MDL_MU1)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.28)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_MU3)
        PMASS(4)=ABS(MDL_MU2)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.29)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_ME1)
        PMASS(4)=ABS(MDL_ME2)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.30)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_ME1)
        PMASS(4)=ABS(MDL_ME3)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.31)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_ME2)
        PMASS(4)=ABS(MDL_ME1)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.32)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_ME2)
        PMASS(4)=ABS(MDL_ME3)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.33)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_ME3)
        PMASS(4)=ABS(MDL_ME1)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.34)) THEN
        PMASS(1)=ABS(MDL_MCHI1)
        PMASS(2)=ABS(MDL_MCHI1)
        PMASS(3)=ABS(MDL_ME3)
        PMASS(4)=ABS(MDL_ME2)

      ENDIF

      RETURN
      END



C     -----------------------------------------------------------------
C     --------c
      SUBROUTINE GETFSMASSES_DM2DM(PMASS, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine which is dynamically generated by the MadDM
C      python     c
C     codes reads through the pmass.inc files to get the external
C      particle   c
C     masses for the DM -> DM processes.                              
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'

C     input parameters
      INTEGER I, J, K

C     PMASS_MADDM2 --- generates series of if-then-else to read
C      appropriate final state masses



      RETURN
      END



C     -----------------------------------------------------------------
C     --------c
      SUBROUTINE GETFSMASSES_SCATTERING(PMASS, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine which is dynamically generated by the MadDM
C      python     c
C     codes reads through the pmass.inc files to get the external
C      particle   c
C     masses for the DM/SM scattering processes.                      
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'

C     input parameters
      INTEGER I, J, K

C     PMASS_MADDM3 --- generates series of if-then-else to read
C      appropriate final state masses



      RETURN
      END




C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_ANN(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an individual       
C            c
C     annihlation process.                                            
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K

C     SMATRIX_MADDM1 --- generates series of if-then-else statements
C      to call appropriate smatrix
      IF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.1)) THEN
        CALL CHI1CHI1_ZZ_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.2)) THEN
        CALL CHI1CHI1_ZH_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.3)) THEN
        CALL CHI1CHI1_HH_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.4)) THEN
        CALL CHI1CHI1_WPWM_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.5)) THEN
        CALL CHI1CHI1_DDX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.6)) THEN
        CALL CHI1CHI1_UUX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.7)) THEN
        CALL CHI1CHI1_SSX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.8)) THEN
        CALL CHI1CHI1_CCX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.9)) THEN
        CALL CHI1CHI1_BBX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.10)) THEN
        CALL CHI1CHI1_TTX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.11)) THEN
        CALL CHI1CHI1_EMEP_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.12)) THEN
        CALL CHI1CHI1_MUMMUP_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.13)) THEN
        CALL CHI1CHI1_TAMTAP_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.14)) THEN
        CALL CHI1CHI1_GG_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.15)) THEN
        CALL CHI1CHI1_AA_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.16)) THEN
        CALL CHI1CHI1_VEVEX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.17)) THEN
        CALL CHI1CHI1_DSX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.18)) THEN
        CALL CHI1CHI1_DBX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.19)) THEN
        CALL CHI1CHI1_UCX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.20)) THEN
        CALL CHI1CHI1_UTX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.21)) THEN
        CALL CHI1CHI1_SDX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.22)) THEN
        CALL CHI1CHI1_SBX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.23)) THEN
        CALL CHI1CHI1_CUX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.24)) THEN
        CALL CHI1CHI1_CTX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.25)) THEN
        CALL CHI1CHI1_BDX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.26)) THEN
        CALL CHI1CHI1_BSX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.27)) THEN
        CALL CHI1CHI1_TUX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.28)) THEN
        CALL CHI1CHI1_TCX_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.29)) THEN
        CALL CHI1CHI1_EMMUP_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.30)) THEN
        CALL CHI1CHI1_EMTAP_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.31)) THEN
        CALL CHI1CHI1_MUMEP_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.32)) THEN
        CALL CHI1CHI1_MUMTAP_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.33)) THEN
        CALL CHI1CHI1_TAMEP_SMATRIX(P_EXT,SMATRIX)
      ELSEIF ((I.EQ.1) .AND. (J.EQ.1) .AND. (K.EQ.34)) THEN
        CALL CHI1CHI1_TAMMUP_SMATRIX(P_EXT,SMATRIX)

      ENDIF

      SMATRIX_ANN = SMATRIX
      RETURN
      END



C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_DM2DM(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an idividual DM ->
C      DM      c
C     process.                                                        
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K


C     SMATRIX_MADDM2 --- generates series of if-then-else statements
C      to call appropriate smatrix



      SMATRIX_DM2DM = SMATRIX
      RETURN
      END



C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_SCATTERING(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an indiviudual DM/SM
C            c
C     scattering process.                                             
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K


C     SMATRIX_MADDM3 --- generates series of if-then-else statements
C      to call appropriate smatrix



      SMATRIX_SCATTERING = SMATRIX
      RETURN
      END

C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_DD(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an indiviudual DM/SM
C            c
C     scattering process relevant for direct detection.               
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K

C     SMATRIX_MADDM_DD --- generates series of if-then-else statements
C      to call appropriate smatrix



      SMATRIX_DD = SMATRIX
      RETURN
      END

C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_DD_EFF(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an indiviudual DM/SM
C            c
C     scattering process in the effective operator framework          
C            c
C     relevant for direct detection.                                  
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K

C     SMATRIX_MADDM_EFF_DD --- generates series of if-then-else
C      statements to call appropriate smatrix



      SMATRIX_DD_EFF = SMATRIX
      RETURN
      END

C     -----------------------------------------------------------------
C     --------c
      FUNCTION SMATRIX_DD_TOT(P_EXT, I, J, K)
C     -----------------------------------------------------------------
C     --------c
C     c
C     This subroutine is generated dynamically by MadDM python scripts
C      that  c
C     are set up to call the individual matrix element subroutines as
C      they   c
C     are generated by MadGraph.                                      
C            c
C     c
C     This function returns the smatrix value for an indiviudual DM/SM
C            c
C     scattering process for the effective + full lagrangian          
C            c
C     relevant for direct detection.                                  
C            c
C     c
C     -----------------------------------------------------------------
C     --------c
      IMPLICIT NONE
      INCLUDE 'maddm.inc'
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION SMATRIX
C     input parameters
      DOUBLE PRECISION P_EXT(0:3,4)
      INTEGER I, J, K

C     SMATRIX_MADDM_TOT_DD --- generates series of if-then-else
C      statements to call appropriate smatrix



      SMATRIX_DD_TOT = SMATRIX
      RETURN
      END

